/* ═══════════════════════════════════════════
   HABLA — questions.js
   390 questions · 13 catégories · 3 niveaux (A0 / A2 / B1)
   Pour ajouter du contenu : modifier CE fichier uniquement.
═══════════════════════════════════════════ */

/* ── Onboarding ── */
const OB_STEPS = [
  { emoji:"🎯", title:"Quel est ton objectif ?", sub:"Choisis ton but principal",
    choices:[{icon:"✈️",text:"Voyager en Espagne"},{icon:"💼",text:"Travailler en espagnol"},{icon:"🎬",text:"Comprendre les films"},{icon:"🏆",text:"Maîtriser la langue"}] },
  { emoji:"⏰", title:"Combien de temps par jour ?", sub:"Adapte à ton emploi du temps",
    choices:[{icon:"⚡",text:"5 min / jour"},{icon:"🔥",text:"10 min / jour"},{icon:"💪",text:"20 min / jour"},{icon:"🚀",text:"30 min+"}] },
  { emoji:"🧠", title:"Ton niveau actuel ?", sub:"Sois honnête pour personnaliser",
    choices:[{icon:"🌱",text:"Zéro connaissance"},{icon:"🌿",text:"Quelques mots"},{icon:"🌳",text:"Bases acquises"},{icon:"🏔️",text:"Intermédiaire+"}] },
];

/* ── Test de niveau (5 questions MCQ) ── */
const TEST_QUESTIONS = [
  {cat:"VOCABULAIRE", q:"Que signifie 'Hola' ?",          opts:["Bonjour","Au revoir","Merci","S'il vous plait"], ans:0},
  {cat:"VOCABULAIRE", q:"Quel mot signifie 'maison' ?",   opts:["perro","casa","agua","libro"],                    ans:1},
  {cat:"GRAMMAIRE",   q:"Complete : 'Yo ___ español'",    opts:["habla","hablo","hablas","hablan"],                ans:1},
  {cat:"TRADUCTION",  q:"Traduis : 'El gato es negro'",   opts:["Le chien est blanc","Le chat est noir","Le chien est noir","Le chat est blanc"], ans:1},
  {cat:"VOCABULAIRE", q:"Quel mot designe 'eau' ?",       opts:["leche","vino","agua","zumo"],                    ans:2},
];

/* ── Leçons ── */
const LESSONS = {
  salutations: {
    title: "Salutations", icon: "💬",
    A0: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dit-on bonjour en espagnol ?", "opts": ["hola", "adiós", "gracias", "perdón"], "hint": "= Bonjour", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dit-on au revoir ?", "opts": ["hola", "buenas", "adiós", "por favor"], "hint": "= Au revoir", "ans": 2},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire merci ?", "opts": ["gracias", "hola", "bien", "mal"], "hint": "= Merci", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire s'il te plaît ?", "opts": ["por favor", "gracias", "hola", "adiós"], "hint": "= S'il te plaît", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire bonsoir ?", "opts": ["buenas noches", "buenos días", "hola", "gracias"], "hint": "= Bonsoir", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire bonjour le matin ?", "opts": ["buenos días", "buenas tardes", "buenas noches", "hola"], "hint": "= Bonjour (matin)", "ans": 0},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hola amigo", "audioFr": "bonjour ami", "words": ["bonjour", "ami", "au revoir", "merci", "bien"], "correct": ["bonjour", "ami"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "buenos días", "audioFr": "bonjour", "words": ["bonjour", "bonsoir", "bonne", "nuit", "journée"], "correct": ["bonjour"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "adiós amigo", "audioFr": "au revoir ami", "words": ["au revoir", "ami", "bonjour", "merci", "bien"], "correct": ["au revoir", "ami"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "gracias señor", "audioFr": "merci monsieur", "words": ["merci", "monsieur", "bonjour", "bien", "mal"], "correct": ["merci", "monsieur"]},
    ],
    A2: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'comment ça va ?'", "opts": ["¿cómo estás?", "¿dónde vas?", "¿qué comes?", "¿cuánto cuesta?"], "hint": "= Comment ça va ?", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Réponse correcte à '¿cómo estás?'", "opts": ["estoy bien", "voy casa", "como pan", "soy alto"], "hint": "= Je vais bien", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'enchanté'", "opts": ["encantado", "cansado", "ocupado", "cerrado"], "hint": "= Enchanté", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'à bientôt'", "opts": ["hasta luego", "hasta nunca", "hola", "gracias"], "hint": "= À bientôt", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'bonne après-midi'", "opts": ["buenas tardes", "buenos días", "buenas noches", "hola"], "hint": "= Bonne après-midi", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'ça va bien'", "opts": ["está bien", "soy bien", "estoy bien", "tengo bien"], "hint": "= Je vais bien", "ans": 2},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "¿cómo estás hoy?", "audioFr": "comment vas-tu aujourd'hui", "words": ["comment", "vas-tu", "aujourd'hui", "hier", "bien", "mal"], "correct": ["comment", "vas-tu", "aujourd'hui"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "estoy muy bien", "audioFr": "je vais très bien", "words": ["je", "vais", "très", "bien", "mal", "suis"], "correct": ["je", "vais", "très", "bien"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hasta mañana amigo", "audioFr": "à demain ami", "words": ["à", "demain", "ami", "aujourd'hui", "bien"], "correct": ["à", "demain", "ami"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "buenas tardes señor", "audioFr": "bon après-midi monsieur", "words": ["bon", "après-midi", "monsieur", "matin", "bonjour"], "correct": ["bon", "après-midi", "monsieur"]},
    ],
    B1: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Choisis la forme formelle correcte", "opts": ["¿cómo está usted?", "¿cómo estás tú?", "¿cómo eres?", "¿cómo vas?"], "hint": "= Comment allez-vous ?", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'j'espère que tu vas bien'", "opts": ["espero que estés bien", "quiero que estás bien", "creo que estás bien", "digo que estás bien"], "hint": "= J'espère que tu vas bien", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Expression pour dire 'ça fait longtemps'", "opts": ["hace mucho tiempo", "mucho hace tiempo", "tiempo hace mucho", "hace tiempo mucho"], "hint": "= Ça fait longtemps", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Choisir la bonne nuance", "opts": ["me alegro de verte", "me gusto verte", "me gusta verte ayer", "me alegró verte mañana"], "hint": "= Je suis content de te voir", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Traduction de 'je suis ravi de vous rencontrer'", "opts": ["estoy encantado de conocerle", "soy encantado conocer", "estoy conocerle", "soy encantado de verte"], "hint": "= Je suis enchanté de vous connaître", "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Quelle phrase est correcte ?", "opts": ["espero verte pronto", "espero ver tú pronto", "espero tú verte pronto", "espero verte prontos"], "hint": "= J'espère te voir bientôt", "ans": 0},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "espero que estés bien hoy", "audioFr": "j'espère que tu vas bien aujourd'hui", "words": ["j'espère", "que", "tu", "vas", "bien", "aujourd'hui", "mal"], "correct": ["j'espère", "que", "tu", "vas", "bien", "aujourd'hui"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "me alegro de verte otra vez", "audioFr": "je suis content de te revoir", "words": ["je", "suis", "content", "de", "te", "revoir", "hier"], "correct": ["je", "suis", "content", "de", "te", "revoir"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hace mucho tiempo que no te veo", "audioFr": "ça fait longtemps que je ne t'ai pas vu", "words": ["ça", "fait", "longtemps", "que", "je", "ne", "t'ai", "pas", "vu", "hier"], "correct": ["ça", "fait", "longtemps", "que", "je", "ne", "t'ai", "pas", "vu"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "encantado de conocerle señor", "audioFr": "ravi de vous rencontrer monsieur", "words": ["ravi", "de", "vous", "rencontrer", "monsieur", "bonjour"], "correct": ["ravi", "de", "vous", "rencontrer", "monsieur"]},
    ],
  },

  nourriture: {
    title: "Nourriture", icon: "🍎",
    A0: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on pain en espagnol ?", "opts": ["pan", "queso", "agua", "pollo"], "hint": "= Le pain", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on eau ?", "opts": ["vino", "leche", "agua", "café"], "hint": "= L'eau", "ans": 2},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on poulet ?", "opts": ["carne", "pollo", "pescado", "pan"], "hint": "= Le poulet", "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on fromage ?", "opts": ["queso", "pan", "leche", "huevo"], "hint": "= Le fromage", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on lait ?", "opts": ["agua", "leche", "vino", "café"], "hint": "= Le lait", "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on café ?", "opts": ["té", "café", "leche", "agua"], "hint": "= Le café", "ans": 1},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como pan", "audioFr": "je mange du pain", "words": ["je", "mange", "du", "pain", "bois", "fromage"], "correct": ["je", "mange", "du", "pain"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo agua", "audioFr": "je bois de l'eau", "words": ["je", "bois", "de", "l'eau", "mange", "lait"], "correct": ["je", "bois", "de", "l'eau"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como queso", "audioFr": "je mange du fromage", "words": ["je", "mange", "du", "fromage", "pain", "poulet"], "correct": ["je", "mange", "du", "fromage"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo leche", "audioFr": "je bois du lait", "words": ["je", "bois", "du", "lait", "eau", "vin"], "correct": ["je", "bois", "du", "lait"]},
    ],
    A2: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange une pomme' ?", "opts": ["como una manzana", "bebo una manzana", "tengo una manzana", "voy una manzana"], "hint": "= Je mange une pomme", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je bois du café' ?", "opts": ["como café", "bebo café", "tengo café", "voy café"], "hint": "= Je bois du café", "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange du riz' ?", "opts": ["como arroz", "bebo arroz", "voy arroz", "tengo arroz"], "hint": "= Je mange du riz", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je bois du lait le matin' ?", "opts": ["bebo leche por la mañana", "como leche por la mañana", "voy leche mañana", "tengo leche mañana"], "hint": "= Je bois du lait le matin", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange au restaurant' ?", "opts": ["como en el restaurante", "bebo en restaurante", "voy restaurante como", "tengo restaurante"], "hint": "= Je mange au restaurant", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je prends un café' ?", "opts": ["tomo un café", "como un café", "bebo un café", "voy un café"], "hint": "= Je prends un café", "ans": 0},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como arroz y pollo", "audioFr": "je mange du riz et du poulet", "words": ["je", "mange", "du", "riz", "et", "du", "poulet", "pain"], "correct": ["je", "mange", "du", "riz", "et", "du", "poulet"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo café por la mañana", "audioFr": "je bois du café le matin", "words": ["je", "bois", "du", "café", "le", "matin", "soir"], "correct": ["je", "bois", "du", "café", "le", "matin"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como en el restaurante", "audioFr": "je mange au restaurant", "words": ["je", "mange", "au", "restaurant", "maison", "vais"], "correct": ["je", "mange", "au", "restaurant"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "tomo una cerveza fría", "audioFr": "je prends une bière froide", "words": ["je", "prends", "une", "bière", "froide", "chaude", "pain"], "correct": ["je", "prends", "une", "bière", "froide"]},
    ],
    B1: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je voudrais manger quelque chose' ?", "opts": ["me gustaría comer algo", "quiero comer algo", "voy comer algo", "tengo comer algo"], "hint": "= Je voudrais manger quelque chose", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Choisis la phrase correcte", "opts": ["prefiero comer en casa", "prefiero comer en casa ayer", "prefiero comer casa en", "prefiero casa comer"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'j'ai trop mangé' ?", "opts": ["he comido demasiado", "como demasiado", "voy comer demasiado", "comía demasiado"], "hint": "= J'ai trop mangé", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je vais manger plus tard' ?", "opts": ["voy a comer más tarde", "voy comer más tarde", "voy a comer tarde más", "voy a más tarde comer"], "hint": "= Je vais manger plus tard", "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Choisis la bonne phrase", "opts": ["es importante que comas bien", "es importante que comes bien", "es importante comer que bien", "es importante que comer bien"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mangeais quand tu es arrivé' ?", "opts": ["comía cuando llegaste", "como cuando llegaste", "comí cuando llegaste", "comeré cuando llegaste"], "hint": "= Je mangeais quand tu es arrivé", "ans": 0},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "he comido demasiado hoy", "audioFr": "j'ai trop mangé aujourd'hui", "words": ["j'ai", "trop", "mangé", "aujourd'hui", "hier", "peu"], "correct": ["j'ai", "trop", "mangé", "aujourd'hui"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "voy a comer más tarde", "audioFr": "je vais manger plus tard", "words": ["je", "vais", "manger", "plus", "tard", "hier"], "correct": ["je", "vais", "manger", "plus", "tard"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "es importante que comas bien", "audioFr": "il est important que tu manges bien", "words": ["il", "est", "important", "que", "tu", "manges", "bien", "viens"], "correct": ["il", "est", "important", "que", "tu", "manges", "bien"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "prefiero comer en casa", "audioFr": "je préfère manger à la maison", "words": ["je", "préfère", "manger", "à", "la", "maison", "restaurant"], "correct": ["je", "préfère", "manger", "à", "la", "maison"]},
    ],
  },

  maison: {
    title: "La maison", icon: "🏠",
    A0: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on maison en espagnol ?", "opts": ["casa", "puerta", "mesa", "cama"], "hint": "= La maison", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on porte ?", "opts": ["ventana", "puerta", "cocina", "baño"], "hint": "= La porte", "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on fenêtre ?", "opts": ["puerta", "ventana", "mesa", "silla"], "hint": "= La fenêtre", "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on lit ?", "opts": ["mesa", "cama", "silla", "sofá"], "hint": "= Le lit", "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on table ?", "opts": ["mesa", "cama", "puerta", "baño"], "hint": "= La table", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on cuisine ?", "opts": ["baño", "cocina", "salón", "puerta"], "hint": "= La cuisine", "ans": 1},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "mi casa", "audioFr": "ma maison", "words": ["ma", "maison", "ta", "table", "porte"], "correct": ["ma", "maison"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la puerta", "audioFr": "la porte", "words": ["la", "porte", "fenêtre", "maison", "table"], "correct": ["la", "porte"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la cama", "audioFr": "le lit", "words": ["le", "lit", "table", "chaise", "porte"], "correct": ["le", "lit"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la cocina", "audioFr": "la cuisine", "words": ["la", "cuisine", "salle", "de", "bain", "table"], "correct": ["la", "cuisine"]},
    ],
    A2: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la maison est grande' ?", "opts": ["la casa es grande", "la casa está grande", "la casa grande es", "es casa grande"], "hint": "= La maison est grande", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je suis dans la maison' ?", "opts": ["estoy en la casa", "soy en la casa", "voy en la casa", "tengo la casa"], "hint": "= Je suis dans la maison", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la porte est ouverte' ?", "opts": ["la puerta está abierta", "la puerta es abierta", "la puerta abierta está", "es puerta abierta"], "hint": "= La porte est ouverte", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je dors dans le lit' ?", "opts": ["duermo en la cama", "duermo la cama", "estoy dormir cama", "soy en la cama"], "hint": "= Je dors dans le lit", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la cuisine est petite' ?", "opts": ["la cocina es pequeña", "la cocina está pequeña", "la cocina pequeña está", "es cocina pequeña"], "hint": "= La cuisine est petite", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je mange dans la cuisine' ?", "opts": ["como en la cocina", "como la cocina", "voy cocina como", "tengo cocina"], "hint": "= Je mange dans la cuisine", "ans": 0},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "estoy en la casa", "audioFr": "je suis dans la maison", "words": ["je", "suis", "dans", "la", "maison", "vais", "cuisine"], "correct": ["je", "suis", "dans", "la", "maison"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la puerta está abierta", "audioFr": "la porte est ouverte", "words": ["la", "porte", "est", "ouverte", "fermée", "maison"], "correct": ["la", "porte", "est", "ouverte"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "duermo en la cama", "audioFr": "je dors dans le lit", "words": ["je", "dors", "dans", "le", "lit", "table", "porte"], "correct": ["je", "dors", "dans", "le", "lit"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "como en la cocina", "audioFr": "je mange dans la cuisine", "words": ["je", "mange", "dans", "la", "cuisine", "salle", "de", "bain"], "correct": ["je", "mange", "dans", "la", "cuisine"]},
    ],
    B1: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je voudrais acheter une maison' ?", "opts": ["me gustaría comprar una casa", "quiero comprar una casa", "voy comprar casa", "tengo comprar casa"], "hint": "= Je voudrais acheter une maison", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Choisis la phrase correcte", "opts": ["la casa en la que vivo es grande", "la casa que vivo es grande", "la casa en vivo es grande", "la casa vivo es grande"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'il faut nettoyer la maison' ?", "opts": ["hay que limpiar la casa", "es limpiar la casa", "tengo limpiar la casa", "voy limpiar la casa"], "hint": "= Il faut nettoyer la maison", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'j'ai vécu dans cette maison' ?", "opts": ["he vivido en esta casa", "vivo en esta casa", "viví en esta casa", "vivía en esta casa"], "hint": "= J'ai vécu dans cette maison", "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Choisis la bonne phrase", "opts": ["es importante que la casa esté limpia", "es importante que la casa está limpia", "es importante la casa esté limpia", "es importante que casa limpia"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la maison où j'ai grandi' ?", "opts": ["la casa donde crecí", "la casa donde crezco", "la casa donde creceré", "la casa donde crecía"], "hint": "= La maison où j'ai grandi", "ans": 0},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "hay que limpiar la casa", "audioFr": "il faut nettoyer la maison", "words": ["il", "faut", "nettoyer", "la", "maison", "manger", "vendre"], "correct": ["il", "faut", "nettoyer", "la", "maison"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "me gustaría comprar una casa", "audioFr": "j'aimerais acheter une maison", "words": ["j'aimerais", "acheter", "une", "maison", "vendre", "louer"], "correct": ["j'aimerais", "acheter", "une", "maison"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la casa donde crecí", "audioFr": "la maison où j'ai grandi", "words": ["la", "maison", "où", "j'ai", "grandi", "vécu", "habité"], "correct": ["la", "maison", "où", "j'ai", "grandi"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "es importante que esté limpia", "audioFr": "il est important qu'elle soit propre", "words": ["il", "est", "important", "qu'elle", "soit", "propre", "grande"], "correct": ["il", "est", "important", "qu'elle", "soit", "propre"]},
    ],
  },

  verbes: {
    title: "Les verbes", icon: "📚",
    A0: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'manger' en espagnol ?", "opts": ["comer", "beber", "vivir", "ir"], "hint": "= Manger", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'boire' ?", "opts": ["comer", "beber", "tener", "hacer"], "hint": "= Boire", "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'aller' ?", "opts": ["ir", "venir", "estar", "ser"], "hint": "= Aller", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'avoir' ?", "opts": ["tener", "ser", "estar", "ir"], "hint": "= Avoir", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'être' (permanent) ?", "opts": ["ser", "estar", "tener", "ir"], "hint": "= Être (état permanent)", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'être' (temporaire) ?", "opts": ["ser", "estar", "ir", "tener"], "hint": "= Être (état temporaire)", "ans": 1},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "quiero comer", "audioFr": "je veux manger", "words": ["je", "veux", "manger", "boire", "aller", "avoir"], "correct": ["je", "veux", "manger"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "voy a beber", "audioFr": "je vais boire", "words": ["je", "vais", "boire", "manger", "avoir"], "correct": ["je", "vais", "boire"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "tengo hambre", "audioFr": "j'ai faim", "words": ["j'ai", "faim", "soif", "froid", "chaud"], "correct": ["j'ai", "faim"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "soy estudiante", "audioFr": "je suis étudiant", "words": ["je", "suis", "étudiant", "professeur", "vais"], "correct": ["je", "suis", "étudiant"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je mange' ?", "opts": ["como", "comes", "come", "comemos"], "hint": "= Je mange", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'tu bois' ?", "opts": ["bebo", "bebes", "bebe", "bebemos"], "hint": "= Tu bois", "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'il va' ?", "opts": ["voy", "vas", "va", "vamos"], "hint": "= Il va", "ans": 2},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'nous avons' ?", "opts": ["tengo", "tienes", "tiene", "tenemos"], "hint": "= Nous avons", "ans": 3},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je suis' (temporaire) ?", "opts": ["soy", "estoy", "tengo", "voy"], "hint": "= Je suis (état temporaire)", "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'ils mangent' ?", "opts": ["como", "comes", "comen", "comemos"], "hint": "= Ils mangent", "ans": 2},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "como en casa", "audioFr": "je mange à la maison", "words": ["je", "mange", "à", "la", "maison", "vais", "bois"], "correct": ["je", "mange", "à", "la", "maison"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "bebes agua fría", "audioFr": "tu bois de l'eau froide", "words": ["tu", "bois", "de", "l'eau", "froide", "chaude", "manges"], "correct": ["tu", "bois", "de", "l'eau", "froide"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "vamos al cine", "audioFr": "nous allons au cinéma", "words": ["nous", "allons", "au", "cinéma", "maison", "vais"], "correct": ["nous", "allons", "au", "cinéma"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "tienen un coche", "audioFr": "ils ont une voiture", "words": ["ils", "ont", "une", "voiture", "maison", "suis"], "correct": ["ils", "ont", "une", "voiture"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'j'ai mangé' ?", "opts": ["he comido", "como", "comí", "comeré"], "hint": "= J'ai mangé (passé composé)", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je mangeais' ?", "opts": ["comía", "como", "comí", "comeré"], "hint": "= Je mangeais (imparfait)", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je vais manger' ?", "opts": ["voy a comer", "voy comer", "comer voy", "voy a comí"], "hint": "= Je vais manger (futur proche)", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Choisis la bonne phrase", "opts": ["quiero que vengas", "quiero que vienes", "quiero vienes", "quiero venir que"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'il faut que tu manges' ?", "opts": ["tienes que comer", "hay que comes", "es que comes", "tienes comer que"], "hint": "= Il faut que tu manges", "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'si j'avais le temps' ?", "opts": ["si tuviera tiempo", "si tengo tiempo", "si tenía tiempo", "si tuve tiempo"], "hint": "= Si j'avais le temps (subjonctif)", "ans": 0},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "he terminado el trabajo", "audioFr": "j'ai terminé le travail", "words": ["j'ai", "terminé", "le", "travail", "hier", "vais"], "correct": ["j'ai", "terminé", "le", "travail"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "voy a salir esta noche", "audioFr": "je vais sortir ce soir", "words": ["je", "vais", "sortir", "ce", "soir", "hier"], "correct": ["je", "vais", "sortir", "ce", "soir"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "quiero que vengas conmigo", "audioFr": "je veux que tu viennes avec moi", "words": ["je", "veux", "que", "tu", "viennes", "avec", "moi", "viens"], "correct": ["je", "veux", "que", "tu", "viennes", "avec", "moi"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "si tuviera tiempo viajaría", "audioFr": "si j'avais le temps je voyagerais", "words": ["si", "j'avais", "le", "temps", "je", "voyagerais", "aurais"], "correct": ["si", "j'avais", "le", "temps", "je", "voyagerais"]},
    ],
  },

  chiffres: {
    title: "Les chiffres", icon: "🔢",
    A0: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 1 en espagnol ?", "opts": ["uno", "dos", "tres", "cuatro"], "hint": "= Un", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 2 ?", "opts": ["uno", "dos", "tres", "cinco"], "hint": "= Deux", "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 3 ?", "opts": ["cuatro", "cinco", "tres", "dos"], "hint": "= Trois", "ans": 2},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 5 ?", "opts": ["cuatro", "cinco", "seis", "siete"], "hint": "= Cinq", "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 10 ?", "opts": ["diez", "once", "doce", "trece"], "hint": "= Dix", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 7 ?", "opts": ["seis", "siete", "ocho", "nueve"], "hint": "= Sept", "ans": 1},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "uno dos tres", "audioFr": "un deux trois", "words": ["un", "deux", "trois", "quatre", "cinq"], "correct": ["un", "deux", "trois"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cinco seis", "audioFr": "cinq six", "words": ["cinq", "six", "sept", "huit", "neuf"], "correct": ["cinq", "six"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "siete ocho", "audioFr": "sept huit", "words": ["sept", "huit", "neuf", "dix", "un"], "correct": ["sept", "huit"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "nueve diez", "audioFr": "neuf dix", "words": ["neuf", "dix", "onze", "douze", "trois"], "correct": ["neuf", "dix"]},
    ],
    A2: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 15 ?", "opts": ["quince", "catorce", "dieciséis", "trece"], "hint": "= Quinze", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 20 ?", "opts": ["veinte", "treinta", "cuarenta", "diez"], "hint": "= Vingt", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 30 ?", "opts": ["veinte", "treinta", "cuarenta", "cincuenta"], "hint": "= Trente", "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 50 ?", "opts": ["cuarenta", "cincuenta", "sesenta", "setenta"], "hint": "= Cinquante", "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 100 ?", "opts": ["cien", "mil", "diez", "ciento"], "hint": "= Cent", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 200 ?", "opts": ["doscientos", "cien", "mil", "trescientos"], "hint": "= Deux cents", "ans": 0},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "tengo veinte años", "audioFr": "j'ai vingt ans", "words": ["j'ai", "vingt", "ans", "trente", "suis"], "correct": ["j'ai", "vingt", "ans"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cuesta treinta euros", "audioFr": "ça coûte trente euros", "words": ["ça", "coûte", "trente", "euros", "vingt", "prix"], "correct": ["ça", "coûte", "trente", "euros"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "somos cinco personas", "audioFr": "nous sommes cinq personnes", "words": ["nous", "sommes", "cinq", "personnes", "deux", "gens"], "correct": ["nous", "sommes", "cinq", "personnes"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "hay cien casas", "audioFr": "il y a cent maisons", "words": ["il", "y", "a", "cent", "maisons", "mille", "deux"], "correct": ["il", "y", "a", "cent", "maisons"]},
    ],
    B1: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'mille' ?", "opts": ["mil", "millón", "cien", "ciento"], "hint": "= Mille", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'un million' ?", "opts": ["mil", "millón", "cien", "millones"], "hint": "= Un million", "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'deux cents' ?", "opts": ["doscientos", "doscientas", "dos cien", "dos cientos"], "hint": "= Deux cents", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Choisis la bonne phrase", "opts": ["hay más de cien personas", "hay más cien personas", "hay de más cien personas", "hay cien más personas"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'moins de vingt' ?", "opts": ["menos de veinte", "menos veinte", "veinte menos", "de menos veinte"], "hint": "= Moins de vingt", "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'environ trente' ?", "opts": ["unos treinta", "treinta unos", "unos de treinta", "treinta de unos"], "hint": "= Environ trente", "ans": 0},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "hay más de cien personas", "audioFr": "il y a plus de cent personnes", "words": ["il", "y", "a", "plus", "de", "cent", "personnes", "moins"], "correct": ["il", "y", "a", "plus", "de", "cent", "personnes"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cuesta unos treinta euros", "audioFr": "ça coûte environ trente euros", "words": ["ça", "coûte", "environ", "trente", "euros", "cent", "prix"], "correct": ["ça", "coûte", "environ", "trente", "euros"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "menos de veinte personas", "audioFr": "moins de vingt personnes", "words": ["moins", "de", "vingt", "personnes", "plus", "cent"], "correct": ["moins", "de", "vingt", "personnes"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "un millón de euros", "audioFr": "un million d'euros", "words": ["un", "million", "d'euros", "mille", "cent"], "correct": ["un", "million", "d'euros"]},
    ],
  },

  famille: {
    title: "La famille", icon: "👨‍👩‍👧",
    A0: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on père en espagnol ?", "opts": ["padre", "madre", "hermano", "abuelo"], "hint": "= Le père", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on mère ?", "opts": ["padre", "madre", "hija", "tío"], "hint": "= La mère", "ans": 1},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on frère ?", "opts": ["hermano", "hermana", "padre", "hijo"], "hint": "= Le frère", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on sœur ?", "opts": ["hermano", "hermana", "madre", "tía"], "hint": "= La sœur", "ans": 1},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on fils ?", "opts": ["hijo", "hija", "padre", "abuelo"], "hint": "= Le fils", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on fille ?", "opts": ["hijo", "hija", "madre", "hermano"], "hint": "= La fille", "ans": 1},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi padre", "audioFr": "mon père", "words": ["mon", "père", "mère", "ton", "frère"], "correct": ["mon", "père"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi madre", "audioFr": "ma mère", "words": ["ma", "mère", "père", "sœur", "ton"], "correct": ["ma", "mère"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi hermano", "audioFr": "mon frère", "words": ["mon", "frère", "sœur", "père", "fils"], "correct": ["mon", "frère"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi hija", "audioFr": "ma fille", "words": ["ma", "fille", "fils", "mère", "grand-mère"], "correct": ["ma", "fille"]},
    ],
    A2: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'ai un frère' ?", "opts": ["tengo un hermano", "soy un hermano", "estoy hermano", "voy hermano"], "hint": "= J'ai un frère", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ma mère travaille' ?", "opts": ["mi madre trabaja", "mi madre trabajo", "mi madre trabajar", "trabaja madre"], "hint": "= Ma mère travaille", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'nous sommes une famille' ?", "opts": ["somos una familia", "soy una familia", "estamos familia", "tenemos familia"], "hint": "= Nous sommes une famille", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'mon père est ici' ?", "opts": ["mi padre está aquí", "mi padre es aquí", "mi padre aquí es", "padre está aquí"], "hint": "= Mon père est ici", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'aime ma famille' ?", "opts": ["me gusta mi familia", "me gusto mi familia", "me gustan familia", "gusta mi familia"], "hint": "= J'aime ma famille", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ils ont deux enfants' ?", "opts": ["tienen dos hijos", "tienen dos hijo", "tienen dos hijas", "tienen dos niño"], "hint": "= Ils ont deux enfants", "ans": 0},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "tengo dos hermanos", "audioFr": "j'ai deux frères", "words": ["j'ai", "deux", "frères", "filles", "père"], "correct": ["j'ai", "deux", "frères"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi madre trabaja mucho", "audioFr": "ma mère travaille beaucoup", "words": ["ma", "mère", "travaille", "beaucoup", "peu", "père"], "correct": ["ma", "mère", "travaille", "beaucoup"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "somos una familia grande", "audioFr": "nous sommes une grande famille", "words": ["nous", "sommes", "une", "grande", "famille", "petite", "suis"], "correct": ["nous", "sommes", "une", "grande", "famille"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi padre está en casa", "audioFr": "mon père est à la maison", "words": ["mon", "père", "est", "à", "la", "maison", "travail"], "correct": ["mon", "père", "est", "à", "la", "maison"]},
    ],
    B1: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'je m'entends bien avec ma famille' ?", "opts": ["me llevo bien con mi familia", "llevo bien mi familia", "me llevo con familia bien", "bien llevo familia"], "hint": "= Je m'entends bien avec ma famille", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'ai grandi avec mes grands-parents' ?", "opts": ["crecí con mis abuelos", "crezco con mis abuelos", "he crecido con mis abuelos", "crecía con mis abuelos"], "hint": "= J'ai grandi avec mes grands-parents", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Choisis la bonne phrase", "opts": ["es importante que la familia esté unida", "es importante que la familia está unida", "es importante la familia esté unida", "familia es importante unida"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ma sœur vit à Madrid' ?", "opts": ["mi hermana vive en Madrid", "mi hermana vive a Madrid", "mi hermana está Madrid", "mi hermana vivir Madrid"], "hint": "= Ma sœur vit à Madrid", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'je rendrai visite à mes parents' ?", "opts": ["visitaré a mis padres", "visito a mis padres", "voy visitar a mis padres", "visitaba a mis padres"], "hint": "= Je rendrai visite à mes parents", "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'nous nous voyons souvent' ?", "opts": ["nos vemos a menudo", "vemos a menudo", "nos vemos mucho a menudo", "vemos nos a menudo"], "hint": "= Nous nous voyons souvent", "ans": 0},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "me llevo bien con mi familia", "audioFr": "je m'entends bien avec ma famille", "words": ["je", "m'entends", "bien", "avec", "ma", "famille", "mal"], "correct": ["je", "m'entends", "bien", "avec", "ma", "famille"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "crecí con mis abuelos", "audioFr": "j'ai grandi avec mes grands-parents", "words": ["j'ai", "grandi", "avec", "mes", "grands-parents", "parents", "vais"], "correct": ["j'ai", "grandi", "avec", "mes", "grands-parents"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "visitaré a mis padres", "audioFr": "je rendrai visite à mes parents", "words": ["je", "rendrai", "visite", "à", "mes", "parents", "visito"], "correct": ["je", "rendrai", "visite", "à", "mes", "parents"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "nos vemos a menudo", "audioFr": "nous nous voyons souvent", "words": ["nous", "nous", "voyons", "souvent", "peu", "bien"], "correct": ["nous", "nous", "voyons", "souvent"]},
    ],
  },

  voyage: {
    title: "Le voyage", icon: "✈️",
    A0: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on train en espagnol ?", "opts": ["tren", "avión", "coche", "barco"], "hint": "= Le train", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on avion ?", "opts": ["barco", "tren", "avión", "taxi"], "hint": "= L'avion", "ans": 2},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on hôtel ?", "opts": ["casa", "hotel", "calle", "ciudad"], "hint": "= L'hôtel", "ans": 1},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on voiture ?", "opts": ["coche", "tren", "avión", "barco"], "hint": "= La voiture", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on billet ?", "opts": ["billete", "maleta", "viaje", "mapa"], "hint": "= Le billet", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on valise ?", "opts": ["mapa", "maleta", "billete", "coche"], "hint": "= La valise", "ans": 1},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "tengo un billete", "audioFr": "j'ai un billet", "words": ["j'ai", "un", "billet", "carte", "valise"], "correct": ["j'ai", "un", "billet"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "el tren", "audioFr": "le train", "words": ["le", "train", "avion", "voiture", "bateau"], "correct": ["le", "train"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "la maleta", "audioFr": "la valise", "words": ["la", "valise", "carte", "maison", "hôtel"], "correct": ["la", "valise"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "el avión", "audioFr": "l'avion", "words": ["l'avion", "train", "voiture", "taxi"], "correct": ["l'avion"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je voyage en train' ?", "opts": ["viajo en tren", "voy en tren", "tengo tren", "viajo tren"], "hint": "= Je voyage en train", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je prends l'avion' ?", "opts": ["tomo el avión", "como el avión", "voy avión", "tengo avión"], "hint": "= Je prends l'avion", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je vais à l'hôtel' ?", "opts": ["voy al hotel", "voy en hotel", "voy hotel", "estoy hotel"], "hint": "= Je vais à l'hôtel", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je prépare ma valise' ?", "opts": ["preparo mi maleta", "preparo maleta", "tengo maleta", "voy maleta"], "hint": "= Je prépare ma valise", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je pars demain' ?", "opts": ["salgo mañana", "voy mañana salir", "tengo salir mañana", "salir mañana voy"], "hint": "= Je pars demain", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je reste à l'hôtel' ?", "opts": ["me quedo en el hotel", "estoy en hotel", "voy en hotel", "tengo hotel"], "hint": "= Je reste à l'hôtel", "ans": 0},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "viajo en avión", "audioFr": "je voyage en avion", "words": ["je", "voyage", "en", "avion", "train", "voiture"], "correct": ["je", "voyage", "en", "avion"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "voy al hotel mañana", "audioFr": "je vais à l'hôtel demain", "words": ["je", "vais", "à", "l'hôtel", "demain", "aujourd'hui", "maison"], "correct": ["je", "vais", "à", "l'hôtel", "demain"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "preparo mi maleta", "audioFr": "je prépare ma valise", "words": ["je", "prépare", "ma", "valise", "carte", "billet"], "correct": ["je", "prépare", "ma", "valise"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "me quedo en el hotel", "audioFr": "je reste à l'hôtel", "words": ["je", "reste", "à", "l'hôtel", "vais", "maison"], "correct": ["je", "reste", "à", "l'hôtel"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'j'aimerais réserver une chambre' ?", "opts": ["me gustaría reservar una habitación", "quiero reservar habitación", "voy reservar habitación", "tengo reservar habitación"], "hint": "= J'aimerais réserver une chambre", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'j'ai perdu mon billet' ?", "opts": ["he perdido mi billete", "pierdo mi billete", "perdí mi billete", "perdía mi billete"], "hint": "= J'ai perdu mon billet", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Choisis la phrase correcte", "opts": ["es mejor que reserves con antelación", "es mejor que reservas con antelación", "es mejor reservar que con antelación", "es mejor que reservar con antelación"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je vais voyager à l'étranger' ?", "opts": ["voy a viajar al extranjero", "voy viajar extranjero", "viajo extranjero", "viajaré extranjero voy"], "hint": "= Je vais voyager à l'étranger", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je suis déjà allé en Espagne' ?", "opts": ["ya he ido a España", "ya fui a España", "ya voy a España", "ya iba a España"], "hint": "= Je suis déjà allé en Espagne", "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'nous avons réservé l'hôtel' ?", "opts": ["hemos reservado el hotel", "reservamos el hotel", "reservábamos el hotel", "reservaremos el hotel"], "hint": "= Nous avons réservé l'hôtel", "ans": 0},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "me gustaría reservar una habitación", "audioFr": "j'aimerais réserver une chambre", "words": ["j'aimerais", "réserver", "une", "chambre", "acheter", "louer"], "correct": ["j'aimerais", "réserver", "une", "chambre"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "he perdido mi billete", "audioFr": "j'ai perdu mon billet", "words": ["j'ai", "perdu", "mon", "billet", "valise", "avons"], "correct": ["j'ai", "perdu", "mon", "billet"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "voy a viajar al extranjero", "audioFr": "je vais voyager à l'étranger", "words": ["je", "vais", "voyager", "à", "l'étranger", "maison"], "correct": ["je", "vais", "voyager", "à", "l'étranger"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "hemos reservado el hotel", "audioFr": "nous avons réservé l'hôtel", "words": ["nous", "avons", "réservé", "l'hôtel", "demain", "vais"], "correct": ["nous", "avons", "réservé", "l'hôtel"]},
    ],
  },

  corps_sante: {
    title: "Corps et santé", icon: "🏥",
    A0: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on tête en espagnol ?", "opts": ["cabeza", "mano", "pie", "ojo"], "hint": "= La tête", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on main ?", "opts": ["pie", "mano", "cabeza", "ojo"], "hint": "= La main", "ans": 1},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on pied ?", "opts": ["mano", "cabeza", "pie", "ojo"], "hint": "= Le pied", "ans": 2},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on oeil ?", "opts": ["nariz", "ojo", "boca", "mano"], "hint": "= L'œil", "ans": 1},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on bouche ?", "opts": ["boca", "nariz", "ojo", "pie"], "hint": "= La bouche", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on nez ?", "opts": ["nariz", "boca", "ojo", "mano"], "hint": "= Le nez", "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "mi mano", "audioFr": "ma main", "words": ["ma", "main", "pied", "tête", "oeil"], "correct": ["ma", "main"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "la cabeza", "audioFr": "la tête", "words": ["la", "tête", "main", "pied", "oeil"], "correct": ["la", "tête"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "el ojo", "audioFr": "l'oeil", "words": ["l'oeil", "bouche", "nez", "main"], "correct": ["l'oeil"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "la boca", "audioFr": "la bouche", "words": ["la", "bouche", "nez", "oeil", "pied"], "correct": ["la", "bouche"]},
    ],
    A2: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'ai mal à la tête' ?", "opts": ["tengo dolor de cabeza", "soy dolor de cabeza", "estoy dolor de cabeza", "voy dolor de cabeza"], "hint": "= J'ai mal à la tête", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'ai mal à la main' ?", "opts": ["tengo dolor de mano", "tengo mano dolor", "soy dolor mano", "estoy dolor de mano"], "hint": "= J'ai mal à la main", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je suis malade' ?", "opts": ["estoy enfermo", "soy enfermo", "tengo enfermo", "voy enfermo"], "hint": "= Je suis malade", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je vais chez le médecin' ?", "opts": ["voy al médico", "voy médico", "soy médico", "tengo médico"], "hint": "= Je vais chez le médecin", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me sens bien' ?", "opts": ["me siento bien", "me siento bueno", "soy bien", "estoy bueno"], "hint": "= Je me sens bien", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je suis fatigué' ?", "opts": ["estoy cansado", "soy cansado", "tengo cansado", "voy cansado"], "hint": "= Je suis fatigué", "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tengo dolor de cabeza", "audioFr": "j'ai mal à la tête", "words": ["j'ai", "mal", "à", "la", "tête", "main", "pied"], "correct": ["j'ai", "mal", "à", "la", "tête"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "estoy enfermo hoy", "audioFr": "je suis malade aujourd'hui", "words": ["je", "suis", "malade", "aujourd'hui", "demain", "bien"], "correct": ["je", "suis", "malade", "aujourd'hui"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "voy al médico", "audioFr": "je vais chez le médecin", "words": ["je", "vais", "chez", "le", "médecin", "maison", "travail"], "correct": ["je", "vais", "chez", "le", "médecin"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "me siento cansado", "audioFr": "je me sens fatigué", "words": ["je", "me", "sens", "fatigué", "bien", "mal"], "correct": ["je", "me", "sens", "fatigué"]},
    ],
    B1: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je dois aller chez le médecin' ?", "opts": ["tengo que ir al médico", "voy ir al médico", "tengo ir médico", "debo voy médico"], "hint": "= Je dois aller chez le médecin", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me suis senti mieux' ?", "opts": ["me he sentido mejor", "me siento mejor", "me sentí mejor", "me sentía mejor"], "hint": "= Je me suis senti mieux", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Choisis la bonne phrase", "opts": ["es importante que descanses", "es importante que descansas", "es importante descansar que", "es importante descansas"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'avais mal hier' ?", "opts": ["tenía dolor ayer", "tengo dolor ayer", "tuve dolor ayer", "tenía dolor mañana"], "hint": "= J'avais mal hier", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me sens mieux aujourd'hui' ?", "opts": ["me siento mejor hoy", "soy mejor hoy", "estoy mejor hoy siento", "me mejor siento hoy"], "hint": "= Je me sens mieux aujourd'hui", "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'il faut que tu te reposes' ?", "opts": ["tienes que descansar", "tienes descansar que", "descansar tienes que", "que tienes descansar"], "hint": "= Il faut que tu te reposes", "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tengo que ir al médico", "audioFr": "je dois aller chez le médecin", "words": ["je", "dois", "aller", "chez", "le", "médecin", "vais"], "correct": ["je", "dois", "aller", "chez", "le", "médecin"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "me he sentido mejor", "audioFr": "je me suis senti mieux", "words": ["je", "me", "suis", "senti", "mieux", "pire", "sois"], "correct": ["je", "me", "suis", "senti", "mieux"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "es importante que descanses", "audioFr": "il est important que tu te reposes", "words": ["il", "est", "important", "que", "tu", "te", "reposes", "viennes"], "correct": ["il", "est", "important", "que", "tu", "te", "reposes"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tenía dolor ayer", "audioFr": "j'avais mal hier", "words": ["j'avais", "mal", "hier", "aujourd'hui", "ai"], "correct": ["j'avais", "mal", "hier"]},
    ],
  },

  metiers: {
    title: "Les métiers", icon: "💼",
    A0: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on médecin en espagnol ?", "opts": ["médico", "profesor", "ingeniero", "cocinero"], "hint": "= Le médecin", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on professeur ?", "opts": ["médico", "profesor", "abogado", "policía"], "hint": "= Le professeur", "ans": 1},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on cuisinier ?", "opts": ["cocinero", "doctor", "maestro", "taxista"], "hint": "= Le cuisinier", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on avocat ?", "opts": ["abogado", "ingeniero", "profesor", "policía"], "hint": "= L'avocat", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on policier ?", "opts": ["policía", "bombero", "médico", "taxista"], "hint": "= Le policier", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on chauffeur de taxi ?", "opts": ["taxista", "conductor", "piloto", "mecánico"], "hint": "= Le chauffeur de taxi", "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy médico", "audioFr": "je suis médecin", "words": ["je", "suis", "médecin", "professeur", "estoy", "travaille"], "correct": ["je", "suis", "médecin"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy profesor", "audioFr": "je suis professeur", "words": ["je", "suis", "professeur", "avocat", "médecin", "travaille"], "correct": ["je", "suis", "professeur"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy cocinero", "audioFr": "je suis cuisinier", "words": ["je", "suis", "cuisinier", "taxi", "médecin", "travaille"], "correct": ["je", "suis", "cuisinier"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy policía", "audioFr": "je suis policier", "words": ["je", "suis", "policier", "pompier", "taxi", "professeur"], "correct": ["je", "suis", "policier"]},
    ],
    A2: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je suis ingénieur' ?", "opts": ["soy ingeniero", "estoy ingeniero", "tengo ingeniero", "voy ingeniero"], "hint": "= Je suis ingénieur", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'elle est médecin' ?", "opts": ["es médica", "está médica", "soy médica", "tiene médica"], "hint": "= Elle est médecin", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je travaille comme professeur' ?", "opts": ["trabajo como profesor", "soy trabajo profesor", "trabajo profesor como", "tengo profesor trabajo"], "hint": "= Je travaille comme professeur", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'il est policier' ?", "opts": ["es policía", "está policía", "soy policía", "tiene policía"], "hint": "= Il est policier", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'nous sommes avocats' ?", "opts": ["somos abogados", "estamos abogados", "tenemos abogados", "vamos abogados"], "hint": "= Nous sommes avocats", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je suis cuisinier' ?", "opts": ["soy cocinero", "estoy cocinero", "tengo cocinero", "voy cocinero"], "hint": "= Je suis cuisinier", "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "trabajo como ingeniero", "audioFr": "je travaille comme ingénieur", "words": ["je", "travaille", "comme", "ingénieur", "médecin", "suis"], "correct": ["je", "travaille", "comme", "ingénieur"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "es médico en el hospital", "audioFr": "il est médecin à l'hôpital", "words": ["il", "est", "médecin", "à", "l'hôpital", "école"], "correct": ["il", "est", "médecin", "à", "l'hôpital"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "somos abogados", "audioFr": "nous sommes avocats", "words": ["nous", "sommes", "avocats", "professeurs", "médecins", "suis"], "correct": ["nous", "sommes", "avocats"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy cocinero en un restaurante", "audioFr": "je suis cuisinier dans un restaurant", "words": ["je", "suis", "cuisinier", "dans", "un", "restaurant", "maison"], "correct": ["je", "suis", "cuisinier", "dans", "un", "restaurant"]},
    ],
    B1: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'j'aimerais devenir ingénieur' ?", "opts": ["me gustaría ser ingeniero", "quiero ser ingeniero", "voy ser ingeniero", "tengo ser ingeniero"], "hint": "= J'aimerais devenir ingénieur", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je travaille depuis deux ans' ?", "opts": ["trabajo desde hace dos años", "trabajo desde dos años", "trabajo hace dos años", "trabajo por dos años"], "hint": "= Je travaille depuis deux ans", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Choisis la bonne phrase", "opts": ["es importante que trabajes bien", "es importante que trabajas bien", "es importante trabajar que bien", "es importante trabajas bien"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'j'ai changé de travail' ?", "opts": ["he cambiado de trabajo", "cambio de trabajo", "cambié trabajo", "cambiaba de trabajo"], "hint": "= J'ai changé de travail", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je vais chercher un travail' ?", "opts": ["voy a buscar trabajo", "voy buscar trabajo", "busco voy trabajo", "voy trabajo buscar"], "hint": "= Je vais chercher un travail", "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'il faut travailler dur' ?", "opts": ["hay que trabajar duro", "es trabajar duro", "tengo trabajar duro", "voy trabajar duro"], "hint": "= Il faut travailler dur", "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "me gustaría ser ingeniero", "audioFr": "j'aimerais devenir ingénieur", "words": ["j'aimerais", "devenir", "ingénieur", "travaille", "suis"], "correct": ["j'aimerais", "devenir", "ingénieur"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "trabajo desde hace dos años", "audioFr": "je travaille depuis deux ans", "words": ["je", "travaille", "depuis", "deux", "ans", "mois"], "correct": ["je", "travaille", "depuis", "deux", "ans"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "he cambiado de trabajo", "audioFr": "j'ai changé de travail", "words": ["j'ai", "changé", "de", "travail", "cherche", "avons"], "correct": ["j'ai", "changé", "de", "travail"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "voy a buscar trabajo", "audioFr": "je vais chercher un travail", "words": ["je", "vais", "chercher", "un", "travail", "trouve", "avons"], "correct": ["je", "vais", "chercher", "un", "travail"]},
    ],
  },

  ville: {
    title: "La ville", icon: "🏙️",
    A0: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on ville en espagnol ?", "opts": ["ciudad", "calle", "plaza", "parque"], "hint": "= La ville", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on rue ?", "opts": ["plaza", "calle", "ciudad", "parque"], "hint": "= La rue", "ans": 1},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on place ?", "opts": ["calle", "ciudad", "plaza", "parque"], "hint": "= La place", "ans": 2},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on parc ?", "opts": ["parque", "calle", "plaza", "ciudad"], "hint": "= Le parc", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on magasin ?", "opts": ["tienda", "escuela", "hospital", "banco"], "hint": "= Le magasin", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on école ?", "opts": ["hospital", "escuela", "tienda", "banco"], "hint": "= L'école", "ans": 1},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la ciudad", "audioFr": "la ville", "words": ["la", "ville", "rue", "place", "parc"], "correct": ["la", "ville"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la calle", "audioFr": "la rue", "words": ["la", "rue", "place", "ville", "parc"], "correct": ["la", "rue"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "el parque", "audioFr": "le parc", "words": ["le", "parc", "rue", "place", "ville"], "correct": ["le", "parc"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la tienda", "audioFr": "le magasin", "words": ["le", "magasin", "école", "banque", "hôpital"], "correct": ["le", "magasin"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vais en ville' ?", "opts": ["voy a la ciudad", "voy ciudad", "voy en ciudad", "estoy ciudad"], "hint": "= Je vais en ville", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'la rue est longue' ?", "opts": ["la calle es larga", "la calle está larga", "la calle larga es", "es calle larga"], "hint": "= La rue est longue", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je marche dans le parc' ?", "opts": ["camino en el parque", "voy parque", "camino parque", "estoy parque"], "hint": "= Je marche dans le parc", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'le magasin est ouvert' ?", "opts": ["la tienda está abierta", "la tienda es abierta", "la tienda abierta es", "es tienda abierta"], "hint": "= Le magasin est ouvert", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vais à l'école' ?", "opts": ["voy a la escuela", "voy escuela", "voy en escuela", "estoy escuela"], "hint": "= Je vais à l'école", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'il y a un parc' ?", "opts": ["hay un parque", "es un parque", "tiene un parque", "está un parque"], "hint": "= Il y a un parc", "ans": 0},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "voy a la ciudad", "audioFr": "je vais en ville", "words": ["je", "vais", "en", "ville", "parc", "rue"], "correct": ["je", "vais", "en", "ville"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "camino en el parque", "audioFr": "je marche dans le parc", "words": ["je", "marche", "dans", "le", "parc", "rue", "vais"], "correct": ["je", "marche", "dans", "le", "parc"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la tienda está abierta", "audioFr": "le magasin est ouvert", "words": ["le", "magasin", "est", "ouvert", "fermé", "rue"], "correct": ["le", "magasin", "est", "ouvert"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hay un parque", "audioFr": "il y a un parc", "words": ["il", "y", "a", "un", "parc", "ville", "rue"], "correct": ["il", "y", "a", "un", "parc"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vis dans une grande ville' ?", "opts": ["vivo en una gran ciudad", "vivo una ciudad grande", "soy en una ciudad grande", "estoy en gran ciudad"], "hint": "= Je vis dans une grande ville", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'la ville où je suis né' ?", "opts": ["la ciudad donde nací", "la ciudad que nací", "la ciudad donde naceré", "la ciudad nací donde"], "hint": "= La ville où je suis né", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Choisis la bonne phrase", "opts": ["es mejor que vivas en el centro", "es mejor que vives en el centro", "es mejor vivir que en el centro", "es mejor que vivir en el centro"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'il y a beaucoup de monde en ville' ?", "opts": ["hay mucha gente en la ciudad", "hay mucho gente ciudad", "es mucha gente en ciudad", "tiene mucha gente ciudad"], "hint": "= Il y a beaucoup de monde en ville", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je me promène dans la rue' ?", "opts": ["paseo por la calle", "camino la calle", "voy por calle", "paseo calle"], "hint": "= Je me promène dans la rue", "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'nous avons visité la ville' ?", "opts": ["hemos visitado la ciudad", "visitamos la ciudad", "visitábamos la ciudad", "visitaremos la ciudad"], "hint": "= Nous avons visité la ville", "ans": 0},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "vivo en una gran ciudad", "audioFr": "je vis dans une grande ville", "words": ["je", "vis", "dans", "une", "grande", "ville", "village"], "correct": ["je", "vis", "dans", "une", "grande", "ville"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la ciudad donde nací", "audioFr": "la ville où je suis né", "words": ["la", "ville", "où", "je", "suis", "né", "vis", "vais"], "correct": ["la", "ville", "où", "je", "suis", "né"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hay mucha gente en la ciudad", "audioFr": "il y a beaucoup de monde en ville", "words": ["il", "y", "a", "beaucoup", "de", "monde", "en", "ville", "peu"], "correct": ["il", "y", "a", "beaucoup", "de", "monde", "en", "ville"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hemos visitado la ciudad", "audioFr": "nous avons visité la ville", "words": ["nous", "avons", "visité", "la", "ville", "demain", "vais"], "correct": ["nous", "avons", "visité", "la", "ville"]},
    ],
  },

  adjectifs: {
    title: "Les adjectifs", icon: "🎨",
    A0: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on grand en espagnol ?", "opts": ["grande", "pequeño", "bonito", "rápido"], "hint": "= Grand", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on petit ?", "opts": ["grande", "pequeño", "caro", "lento"], "hint": "= Petit", "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on beau ?", "opts": ["feo", "bonito", "caro", "lento"], "hint": "= Beau", "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on cher ?", "opts": ["barato", "caro", "bonito", "rápido"], "hint": "= Cher", "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on rapide ?", "opts": ["lento", "rápido", "grande", "caro"], "hint": "= Rapide", "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on lent ?", "opts": ["rápido", "lento", "bonito", "pequeño"], "hint": "= Lent", "ans": 1},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "coche grande", "audioFr": "voiture grande", "words": ["voiture", "grande", "petite", "rapide", "chère"], "correct": ["voiture", "grande"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "casa pequeña", "audioFr": "maison petite", "words": ["maison", "petite", "grande", "belle", "chère"], "correct": ["maison", "petite"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "libro caro", "audioFr": "livre cher", "words": ["livre", "cher", "pas cher", "beau", "rapide"], "correct": ["livre", "cher"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "coche rápido", "audioFr": "voiture rapide", "words": ["voiture", "rapide", "lente", "grande", "chère"], "correct": ["voiture", "rapide"]},
    ],
    A2: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'la maison est grande' ?", "opts": ["la casa es grande", "la casa está grande", "la casa grande es", "es casa grande"], "hint": "= La maison est grande", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le film est intéressant' ?", "opts": ["la película es interesante", "la película está interesante", "es película interesante", "película es interesante"], "hint": "= Le film est intéressant", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le prix est cher' ?", "opts": ["el precio es caro", "el precio está caro", "precio es caro", "es precio caro"], "hint": "= Le prix est cher", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le service est rapide' ?", "opts": ["el servicio es rápido", "el servicio está rápido", "servicio es rápido", "es servicio rápido"], "hint": "= Le service est rapide", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'la voiture est lente' ?", "opts": ["el coche es lento", "el coche está lento", "coche es lento", "es coche lento"], "hint": "= La voiture est lente", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le livre est bon' ?", "opts": ["el libro es bueno", "el libro está bueno", "libro es bueno", "es libro bueno"], "hint": "= Le livre est bon", "ans": 0},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "la casa es muy grande", "audioFr": "la maison est très grande", "words": ["la", "maison", "est", "très", "grande", "petite"], "correct": ["la", "maison", "est", "très", "grande"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el coche es muy rápido", "audioFr": "la voiture est très rapide", "words": ["la", "voiture", "est", "très", "rapide", "lente"], "correct": ["la", "voiture", "est", "très", "rapide"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el libro es interesante", "audioFr": "le livre est intéressant", "words": ["le", "livre", "est", "intéressant", "ennuyeux", "cher"], "correct": ["le", "livre", "est", "intéressant"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el precio es caro", "audioFr": "le prix est cher", "words": ["le", "prix", "est", "cher", "pas cher", "grand"], "correct": ["le", "prix", "est", "cher"]},
    ],
    B1: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'il est important que ce soit rapide' ?", "opts": ["es importante que sea rápido", "es importante que es rápido", "es importante ser rápido", "es importante que está rápido"], "hint": "= Il est important que ce soit rapide", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'c'était très intéressant' ?", "opts": ["era muy interesante", "es muy interesante", "fue muy interesante", "será interesante"], "hint": "= C'était très intéressant", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Choisis la bonne phrase", "opts": ["es mejor que sea barato", "es mejor que es barato", "es mejor ser barato", "es mejor que está barato"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'il devient de plus en plus rapide' ?", "opts": ["se vuelve cada vez más rápido", "es cada vez rápido", "se vuelve más cada rápido", "es cada vez más rápido"], "hint": "= Il devient de plus en plus rapide", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'je trouve ce film ennuyeux' ?", "opts": ["encuentro esta película aburrida", "encuentro película aburrido", "encuentro esta película aburrido", "película encuentro aburrida"], "hint": "= Je trouve ce film ennuyeux", "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'c'est trop cher' ?", "opts": ["es demasiado caro", "es muy caro demasiado", "es caro muy", "es demasiado mucho caro"], "hint": "= C'est trop cher", "ans": 0},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "es importante que sea rápido", "audioFr": "il est important que ce soit rapide", "words": ["il", "est", "important", "que", "ce", "soit", "rapide", "lent"], "correct": ["il", "est", "important", "que", "ce", "soit", "rapide"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "era muy interesante", "audioFr": "c'était très intéressant", "words": ["c'était", "très", "intéressant", "est", "était"], "correct": ["c'était", "très", "intéressant"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "se vuelve cada vez más rápido", "audioFr": "il devient de plus en plus rapide", "words": ["il", "devient", "de", "plus", "en", "rapide", "moins"], "correct": ["il", "devient", "de", "plus", "en", "plus", "rapide"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "es demasiado caro", "audioFr": "c'est trop cher", "words": ["c'est", "trop", "cher", "très", "pas cher"], "correct": ["c'est", "trop", "cher"]},
    ],
  },

  adverbes: {
    title: "Les adverbes", icon: "⚡",
    A0: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on très en espagnol ?", "opts": ["muy", "poco", "bien", "mal"], "hint": "= Très", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on bien ?", "opts": ["bien", "mal", "muy", "poco"], "hint": "= Bien", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on mal ?", "opts": ["bien", "mal", "muy", "mucho"], "hint": "= Mal", "ans": 1},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on peu ?", "opts": ["mucho", "poco", "bien", "mal"], "hint": "= Peu", "ans": 1},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on beaucoup ?", "opts": ["mucho", "poco", "bien", "mal"], "hint": "= Beaucoup", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on ici ?", "opts": ["aquí", "allí", "bien", "mal"], "hint": "= Ici", "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "muy bien", "audioFr": "très bien", "words": ["très", "bien", "mal", "peu", "beaucoup"], "correct": ["très", "bien"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "muy mal", "audioFr": "très mal", "words": ["très", "mal", "bien", "peu", "beaucoup"], "correct": ["très", "mal"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "mucho pan", "audioFr": "beaucoup de pain", "words": ["beaucoup", "de", "pain", "peu", "bien", "mal"], "correct": ["beaucoup", "de", "pain"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "aquí ahora", "audioFr": "ici maintenant", "words": ["ici", "maintenant", "là", "demain", "bien"], "correct": ["ici", "maintenant"]},
    ],
    A2: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je mange souvent' ?", "opts": ["como a menudo", "como siempre", "como mucho", "como poco"], "hint": "= Je mange souvent", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille beaucoup' ?", "opts": ["trabajo mucho", "trabajo poco", "trabajo bien", "trabajo mal"], "hint": "= Je travaille beaucoup", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je parle bien' ?", "opts": ["hablo bien", "hablo mal", "hablo mucho", "hablo poco"], "hint": "= Je parle bien", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je dors mal' ?", "opts": ["duermo mal", "duermo bien", "duermo mucho", "duermo poco"], "hint": "= Je dors mal", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je viens ici' ?", "opts": ["vengo aquí", "vengo allí", "voy aquí", "voy allí"], "hint": "= Je viens ici", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je pars maintenant' ?", "opts": ["salgo ahora", "salgo mañana", "salgo ayer", "salgo siempre"], "hint": "= Je pars maintenant", "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "como a menudo", "audioFr": "je mange souvent", "words": ["je", "mange", "souvent", "toujours", "jamais"], "correct": ["je", "mange", "souvent"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo mucho", "audioFr": "je travaille beaucoup", "words": ["je", "travaille", "beaucoup", "peu", "bien", "mal"], "correct": ["je", "travaille", "beaucoup"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "hablo bien español", "audioFr": "je parle bien espagnol", "words": ["je", "parle", "bien", "espagnol", "mal", "peu"], "correct": ["je", "parle", "bien", "espagnol"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "salgo ahora", "audioFr": "je pars maintenant", "words": ["je", "pars", "maintenant", "demain", "hier", "toujours"], "correct": ["je", "pars", "maintenant"]},
    ],
    B1: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille de plus en plus' ?", "opts": ["trabajo cada vez más", "trabajo más cada vez", "cada vez trabajo más", "trabajo vez más cada"], "hint": "= Je travaille de plus en plus", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je ne viens jamais' ?", "opts": ["no vengo nunca", "no nunca vengo", "nunca no vengo", "vengo nunca no"], "hint": "= Je ne viens jamais", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Choisis la bonne phrase", "opts": ["hablo bastante bien", "hablo bien bastante", "bastante hablo bien", "bien hablo bastante"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je comprends mieux maintenant' ?", "opts": ["entiendo mejor ahora", "entiendo ahora mejor", "mejor entiendo ahora", "entiendo ahora más mejor"], "hint": "= Je comprends mieux maintenant", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille trop' ?", "opts": ["trabajo demasiado", "trabajo muy", "trabajo mucho demasiado", "trabajo demasiado mucho"], "hint": "= Je travaille trop", "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je viens rarement' ?", "opts": ["vengo raramente", "raramente vengo", "vengo poco", "vengo siempre"], "hint": "= Je viens rarement", "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo cada vez más", "audioFr": "je travaille de plus en plus", "words": ["je", "travaille", "de", "plus", "en", "moins", "peu"], "correct": ["je", "travaille", "de", "plus", "en", "plus"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "no vengo nunca", "audioFr": "je ne viens jamais", "words": ["je", "ne", "viens", "jamais", "toujours", "ici"], "correct": ["je", "ne", "viens", "jamais"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "entiendo mejor ahora", "audioFr": "je comprends mieux maintenant", "words": ["je", "comprends", "mieux", "maintenant", "avant", "mal"], "correct": ["je", "comprends", "mieux", "maintenant"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo demasiado", "audioFr": "je travaille trop", "words": ["je", "travaille", "trop", "beaucoup", "peu", "bien"], "correct": ["je", "travaille", "trop"]},
    ],
  },

  expressions: {
    title: "Expressions", icon: "💡",
    A0: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir faim' ?", "opts": ["tener hambre", "estar hambre", "ser hambre", "ir hambre"], "hint": "= Avoir faim → tener hambre", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir soif' ?", "opts": ["tener sed", "estar sed", "ser sed", "ir sed"], "hint": "= Avoir soif → tener sed", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir chaud' ?", "opts": ["tener calor", "estar calor", "ser calor", "ir calor"], "hint": "= Avoir chaud → tener calor", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir froid' ?", "opts": ["tener frío", "estar frío", "ser frío", "ir frío"], "hint": "= Avoir froid → tener frío", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir peur' ?", "opts": ["tener miedo", "estar miedo", "ser miedo", "ir miedo"], "hint": "= Avoir peur → tener miedo", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir raison' ?", "opts": ["tener razón", "estar razón", "ser razón", "ir razón"], "hint": "= Avoir raison → tener razón", "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo hambre", "audioFr": "j'ai faim", "words": ["j'ai", "faim", "soif", "froid", "chaud"], "correct": ["j'ai", "faim"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo sed", "audioFr": "j'ai soif", "words": ["j'ai", "soif", "faim", "froid", "chaud"], "correct": ["j'ai", "soif"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo frío", "audioFr": "j'ai froid", "words": ["j'ai", "froid", "chaud", "faim", "soif"], "correct": ["j'ai", "froid"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo calor", "audioFr": "j'ai chaud", "words": ["j'ai", "chaud", "froid", "faim", "soif"], "correct": ["j'ai", "chaud"]},
    ],
    A2: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca m'est égal' ?", "opts": ["me da igual", "me es igual", "soy igual", "tengo igual"], "hint": "= Ça m'est égal", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'manquer' ?", "opts": ["echar de menos", "tener de menos", "ser de menos", "estar de menos"], "hint": "= Manquer → echar de menos", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'faire attention' ?", "opts": ["tener cuidado", "hacer cuidado", "ser cuidado", "estar cuidado"], "hint": "= Faire attention → tener cuidado", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'se dépêcher' ?", "opts": ["darse prisa", "hacer prisa", "tener prisa", "estar prisa"], "hint": "= Se dépêcher → darse prisa", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir besoin de' ?", "opts": ["tener que", "necesitar", "tener necesidad", "hacer falta"], "hint": "= Avoir besoin de → necesitar", "ans": 1},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'se rendre compte' ?", "opts": ["darse cuenta", "tener cuenta", "hacer cuenta", "estar cuenta"], "hint": "= Se rendre compte → darse cuenta", "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "me da igual", "audioFr": "ca m'est égal", "words": ["ça", "m'est", "égal", "bien", "mal"], "correct": ["ça", "m'est", "égal"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "te echo de menos", "audioFr": "tu me manques", "words": ["tu", "me", "manques", "lui", "bien"], "correct": ["tu", "me", "manques"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "ten cuidado", "audioFr": "fais attention", "words": ["fais", "attention", "vite", "bien", "mal"], "correct": ["fais", "attention"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "date prisa", "audioFr": "dépêche-toi", "words": ["dépêche-toi", "attention", "moins", "égal"], "correct": ["dépêche-toi"]},
    ],
    B1: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca vaut la peine' ?", "opts": ["vale la pena", "vale pena", "es pena", "pena vale"], "hint": "= Ça vaut la peine", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je m'en fiche' ?", "opts": ["me da igual", "me importa", "no me importa", "me gusta"], "hint": "= Je m'en fiche → no me importa", "ans": 2},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Choisis la bonne phrase", "opts": ["merece la pena intentarlo", "merece pena intentarlo", "pena merece intentarlo", "merece intentarlo pena"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je suis en train de le faire' ?", "opts": ["estoy haciéndolo", "soy haciendo", "estoy hacer", "hago lo"], "hint": "= Je suis en train de le faire", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je n'en peux plus' ?", "opts": ["no puedo más", "no más puedo", "no puedo más de", "más no puedo"], "hint": "= Je n'en peux plus", "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca dépend' ?", "opts": ["depende", "es depende", "tiene depende", "está depende"], "hint": "= Ça dépend", "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "vale la pena", "audioFr": "ca vaut la peine", "words": ["ça", "vaut", "la", "peine", "égal", "moins"], "correct": ["ça", "vaut", "la", "peine"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "no puedo más", "audioFr": "je n'en peux plus", "words": ["je", "n'en", "peux", "plus", "moins", "bien"], "correct": ["je", "n'en", "peux", "plus"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "estoy haciéndolo", "audioFr": "je suis en train de le faire", "words": ["je", "suis", "en", "train", "de", "le", "faire", "suis"], "correct": ["je", "suis", "en", "train", "de", "le", "faire"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "depende de la situación", "audioFr": "ca dépend de la situation", "words": ["ça", "dépend", "de", "la", "situation", "toujours", "jamais"], "correct": ["ça", "dépend", "de", "la", "situation"]},
    ],
  },

};
