/* ═══════════════════════════════════════════
   HABLA — questions.js
   390 questions · 13 catégories · 3 niveaux (A0 / A2 / B1)
   Pour ajouter du contenu : modifier CE fichier uniquement.
═══════════════════════════════════════════ */

/* ── Onboarding ── */
const OB_STEPS = [
  { emoji:"🎯", title:"Quel est ton objectif ?", sub:"Choisis ton but principal",
    choices:[{icon:"✈️",text:"Voyager en Espagne"},{icon:"💼",text:"Travailler en espagnol"},{icon:"🎬",text:"Comprendre les films"},{icon:"🏆",text:"Maîtriser la langue"}] },
  { emoji:"⏰", title:"Combien de temps par jour ?", sub:"Adapte à ton emploi du temps",
    choices:[{icon:"⚡",text:"5 min / jour"},{icon:"🔥",text:"10 min / jour"},{icon:"💪",text:"20 min / jour"},{icon:"🚀",text:"30 min+"}] },
  { emoji:"🧠", title:"Ton niveau actuel ?", sub:"Sois honnête pour personnaliser",
    choices:[{icon:"🌱",text:"Zéro connaissance"},{icon:"🌿",text:"Quelques mots"},{icon:"🌳",text:"Bases acquises"},{icon:"🏔️",text:"Intermédiaire+"}] },
];

/* ── Test de niveau (5 questions MCQ) ── */
const TEST_QUESTIONS = [
  {cat:"VOCABULAIRE", q:"Que signifie 'Hola' ?",          opts:["Bonjour","Au revoir","Merci","S'il vous plait"], ans:0},
  {cat:"VOCABULAIRE", q:"Quel mot signifie 'maison' ?",   opts:["perro","casa","agua","libro"],                    ans:1},
  {cat:"GRAMMAIRE",   q:"Complete : 'Yo ___ español'",    opts:["habla","hablo","hablas","hablan"],                ans:1},
  {cat:"TRADUCTION",  q:"Traduis : 'El gato es negro'",   opts:["Le chien est blanc","Le chat est noir","Le chien est noir","Le chat est blanc"], ans:1},
  {cat:"VOCABULAIRE", q:"Quel mot designe 'eau' ?",       opts:["leche","vino","agua","zumo"],                    ans:2},
];

/* ── Leçons ── */
const LESSONS = {
  salutations: {
    title: "Salutations", icon: "💬",
    A0: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dit-on bonjour en espagnol ?", "opts": ["hola", "adiós", "gracias", "perdón"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dit-on au revoir ?", "opts": ["hola", "buenas", "adiós", "por favor"], "ans": 2},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire merci ?", "opts": ["gracias", "hola", "bien", "mal"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire s'il te plaît ?", "opts": ["por favor", "gracias", "hola", "adiós"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire bonsoir ?", "opts": ["buenas noches", "buenos días", "hola", "gracias"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire bonjour le matin ?", "opts": ["buenos días", "buenas tardes", "buenas noches", "hola"], "ans": 0},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hola amigo", "audioFr": "bonjour ami", "words": ["hola", "amigo", "adiós", "gracias", "bien"], "correct": ["hola", "amigo"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "buenos días", "audioFr": "bonjour", "words": ["buenos", "días", "noches", "tardes", "hola"], "correct": ["buenos", "días"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "adiós amigo", "audioFr": "au revoir ami", "words": ["adiós", "amigo", "hola", "gracias", "bien"], "correct": ["adiós", "amigo"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "gracias señor", "audioFr": "merci monsieur", "words": ["gracias", "señor", "hola", "bien", "mal"], "correct": ["gracias", "señor"]},
    ],
    A2: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'comment ça va ?'", "opts": ["¿cómo estás?", "¿dónde vas?", "¿qué comes?", "¿cuánto cuesta?"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Réponse correcte à '¿cómo estás?'", "opts": ["estoy bien", "voy casa", "como pan", "soy alto"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'enchanté'", "opts": ["encantado", "cansado", "ocupado", "cerrado"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'à bientôt'", "opts": ["hasta luego", "hasta nunca", "hola", "gracias"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'bonne après-midi'", "opts": ["buenas tardes", "buenos días", "buenas noches", "hola"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'ça va bien'", "opts": ["está bien", "soy bien", "estoy bien", "tengo bien"], "ans": 2},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "¿cómo estás hoy?", "audioFr": "comment vas-tu aujourd'hui", "words": ["cómo", "estás", "hoy", "ayer", "bien", "mal"], "correct": ["cómo", "estás", "hoy"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "estoy muy bien", "audioFr": "je vais très bien", "words": ["estoy", "muy", "bien", "mal", "soy"], "correct": ["estoy", "muy", "bien"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hasta mañana amigo", "audioFr": "à demain ami", "words": ["hasta", "mañana", "amigo", "hoy", "bien"], "correct": ["hasta", "mañana", "amigo"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "buenas tardes señor", "audioFr": "bon après-midi monsieur", "words": ["buenas", "tardes", "señor", "días", "hola"], "correct": ["buenas", "tardes", "señor"]},
    ],
    B1: [
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Choisis la forme formelle correcte", "opts": ["¿cómo está usted?", "¿cómo estás tú?", "¿cómo eres?", "¿cómo vas?"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Comment dire 'j'espère que tu vas bien'", "opts": ["espero que estés bien", "quiero que estás bien", "creo que estás bien", "digo que estás bien"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Expression pour dire 'ça fait longtemps'", "opts": ["hace mucho tiempo", "mucho hace tiempo", "tiempo hace mucho", "hace tiempo mucho"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Choisir la bonne nuance", "opts": ["me alegro de verte", "me gusto verte", "me gusta verte ayer", "me alegró verte mañana"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Traduction de 'je suis ravi de vous rencontrer'", "opts": ["estoy encantado de conocerle", "soy encantado conocer", "estoy conocerle", "soy encantado de verte"], "ans": 0},
      {"type": "mcq", "cat": "SALUTATIONS", "q": "Quelle phrase est correcte ?", "opts": ["espero verte pronto", "espero ver tú pronto", "espero tú verte pronto", "espero verte prontos"], "ans": 0},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "espero que estés bien hoy", "audioFr": "j'espère que tu vas bien aujourd'hui", "words": ["espero", "que", "estés", "bien", "hoy", "mal"], "correct": ["espero", "que", "estés", "bien", "hoy"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "me alegro de verte otra vez", "audioFr": "je suis content de te revoir", "words": ["me", "alegro", "de", "verte", "otra", "vez", "ayer"], "correct": ["me", "alegro", "de", "verte", "otra", "vez"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "hace mucho tiempo que no te veo", "audioFr": "ça fait longtemps que je ne t'ai pas vu", "words": ["hace", "mucho", "tiempo", "que", "no", "te", "veo", "hoy"], "correct": ["hace", "mucho", "tiempo", "que", "no", "te", "veo"]},
      {"type": "audio", "cat": "SALUTATIONS", "q": "Écoute et traduis la phrase", "audio": "encantado de conocerle señor", "audioFr": "ravi de vous rencontrer monsieur", "words": ["encantado", "de", "conocerle", "señor", "hola", "bien"], "correct": ["encantado", "de", "conocerle", "señor"]},
    ],
  },

  nourriture: {
    title: "Nourriture", icon: "🍎",
    A0: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on pain en espagnol ?", "opts": ["pan", "queso", "agua", "pollo"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on eau ?", "opts": ["vino", "leche", "agua", "café"], "ans": 2},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on poulet ?", "opts": ["carne", "pollo", "pescado", "pan"], "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on fromage ?", "opts": ["queso", "pan", "leche", "huevo"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on lait ?", "opts": ["agua", "leche", "vino", "café"], "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dit-on café ?", "opts": ["té", "café", "leche", "agua"], "ans": 1},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como pan", "audioFr": "je mange du pain", "words": ["como", "pan", "bebo", "agua", "queso"], "correct": ["como", "pan"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo agua", "audioFr": "je bois de l'eau", "words": ["bebo", "agua", "como", "leche", "vino"], "correct": ["bebo", "agua"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como queso", "audioFr": "je mange du fromage", "words": ["como", "queso", "pan", "agua", "pollo"], "correct": ["como", "queso"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo leche", "audioFr": "je bois du lait", "words": ["bebo", "leche", "agua", "vino", "pan"], "correct": ["bebo", "leche"]},
    ],
    A2: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange une pomme' ?", "opts": ["como una manzana", "bebo una manzana", "tengo una manzana", "voy una manzana"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je bois du café' ?", "opts": ["como café", "bebo café", "tengo café", "voy café"], "ans": 1},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange du riz' ?", "opts": ["como arroz", "bebo arroz", "voy arroz", "tengo arroz"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je bois du lait le matin' ?", "opts": ["bebo leche por la mañana", "como leche por la mañana", "voy leche mañana", "tengo leche mañana"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mange au restaurant' ?", "opts": ["como en el restaurante", "bebo en restaurante", "voy restaurante como", "tengo restaurante"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je prends un café' ?", "opts": ["tomo un café", "como un café", "bebo un café", "voy un café"], "ans": 0},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como arroz y pollo", "audioFr": "je mange du riz et du poulet", "words": ["como", "arroz", "y", "pollo", "pan", "agua"], "correct": ["como", "arroz", "y", "pollo"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "bebo café por la mañana", "audioFr": "je bois du café le matin", "words": ["bebo", "café", "por", "la", "mañana", "noche"], "correct": ["bebo", "café", "por", "la", "mañana"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "como en el restaurante", "audioFr": "je mange au restaurant", "words": ["como", "en", "el", "restaurante", "casa", "voy"], "correct": ["como", "en", "el", "restaurante"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "tomo una cerveza fría", "audioFr": "je prends une bière froide", "words": ["tomo", "una", "cerveza", "fría", "caliente", "pan"], "correct": ["tomo", "una", "cerveza", "fría"]},
    ],
    B1: [
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je voudrais manger quelque chose' ?", "opts": ["me gustaría comer algo", "quiero comer algo", "voy comer algo", "tengo comer algo"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Choisis la phrase correcte", "opts": ["prefiero comer en casa", "prefiero comer en casa ayer", "prefiero comer casa en", "prefiero casa comer"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'j'ai trop mangé' ?", "opts": ["he comido demasiado", "como demasiado", "voy comer demasiado", "comía demasiado"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je vais manger plus tard' ?", "opts": ["voy a comer más tarde", "voy comer más tarde", "voy a comer tarde más", "voy a más tarde comer"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Choisis la bonne phrase", "opts": ["es importante que comas bien", "es importante que comes bien", "es importante comer que bien", "es importante que comer bien"], "ans": 0},
      {"type": "mcq", "cat": "NOURRITURE", "q": "Comment dire 'je mangeais quand tu es arrivé' ?", "opts": ["comía cuando llegaste", "como cuando llegaste", "comí cuando llegaste", "comeré cuando llegaste"], "ans": 0},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "he comido demasiado hoy", "audioFr": "j'ai trop mangé aujourd'hui", "words": ["he", "comido", "demasiado", "hoy", "ayer", "poco"], "correct": ["he", "comido", "demasiado", "hoy"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "voy a comer más tarde", "audioFr": "je vais manger plus tard", "words": ["voy", "a", "comer", "más", "tarde", "ayer"], "correct": ["voy", "a", "comer", "más", "tarde"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "es importante que comas bien", "audioFr": "il est important que tu manges bien", "words": ["es", "importante", "que", "comas", "bien", "comes"], "correct": ["es", "importante", "que", "comas", "bien"]},
      {"type": "audio", "cat": "NOURRITURE", "q": "Écoute et traduis la phrase", "audio": "prefiero comer en casa", "audioFr": "je préfère manger à la maison", "words": ["prefiero", "comer", "en", "casa", "restaurante", "voy"], "correct": ["prefiero", "comer", "en", "casa"]},
    ],
  },

  maison: {
    title: "La maison", icon: "🏠",
    A0: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on maison en espagnol ?", "opts": ["casa", "puerta", "mesa", "cama"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on porte ?", "opts": ["ventana", "puerta", "cocina", "baño"], "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on fenêtre ?", "opts": ["puerta", "ventana", "mesa", "silla"], "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on lit ?", "opts": ["mesa", "cama", "silla", "sofá"], "ans": 1},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on table ?", "opts": ["mesa", "cama", "puerta", "baño"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dit-on cuisine ?", "opts": ["baño", "cocina", "salón", "puerta"], "ans": 1},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "mi casa", "audioFr": "ma maison", "words": ["mi", "casa", "tu", "mesa", "puerta"], "correct": ["mi", "casa"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la puerta", "audioFr": "la porte", "words": ["la", "puerta", "ventana", "casa", "mesa"], "correct": ["la", "puerta"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la cama", "audioFr": "le lit", "words": ["la", "cama", "mesa", "silla", "puerta"], "correct": ["la", "cama"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la cocina", "audioFr": "la cuisine", "words": ["la", "cocina", "baño", "mesa", "casa"], "correct": ["la", "cocina"]},
    ],
    A2: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la maison est grande' ?", "opts": ["la casa es grande", "la casa está grande", "la casa grande es", "es casa grande"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je suis dans la maison' ?", "opts": ["estoy en la casa", "soy en la casa", "voy en la casa", "tengo la casa"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la porte est ouverte' ?", "opts": ["la puerta está abierta", "la puerta es abierta", "la puerta abierta está", "es puerta abierta"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je dors dans le lit' ?", "opts": ["duermo en la cama", "duermo la cama", "estoy dormir cama", "soy en la cama"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la cuisine est petite' ?", "opts": ["la cocina es pequeña", "la cocina está pequeña", "la cocina pequeña está", "es cocina pequeña"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je mange dans la cuisine' ?", "opts": ["como en la cocina", "como la cocina", "voy cocina como", "tengo cocina"], "ans": 0},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "estoy en la casa", "audioFr": "je suis dans la maison", "words": ["estoy", "en", "la", "casa", "voy", "cocina"], "correct": ["estoy", "en", "la", "casa"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la puerta está abierta", "audioFr": "la porte est ouverte", "words": ["la", "puerta", "está", "abierta", "cerrada", "casa"], "correct": ["la", "puerta", "está", "abierta"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "duermo en la cama", "audioFr": "je dors dans le lit", "words": ["duermo", "en", "la", "cama", "mesa", "puerta"], "correct": ["duermo", "en", "la", "cama"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "como en la cocina", "audioFr": "je mange dans la cuisine", "words": ["como", "en", "la", "cocina", "baño", "voy"], "correct": ["como", "en", "la", "cocina"]},
    ],
    B1: [
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'je voudrais acheter une maison' ?", "opts": ["me gustaría comprar una casa", "quiero comprar una casa", "voy comprar casa", "tengo comprar casa"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Choisis la phrase correcte", "opts": ["la casa en la que vivo es grande", "la casa que vivo es grande", "la casa en vivo es grande", "la casa vivo es grande"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'il faut nettoyer la maison' ?", "opts": ["hay que limpiar la casa", "es limpiar la casa", "tengo limpiar la casa", "voy limpiar la casa"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'j'ai vécu dans cette maison' ?", "opts": ["he vivido en esta casa", "vivo en esta casa", "viví en esta casa", "vivía en esta casa"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Choisis la bonne phrase", "opts": ["es importante que la casa esté limpia", "es importante que la casa está limpia", "es importante la casa esté limpia", "es importante que casa limpia"], "ans": 0},
      {"type": "mcq", "cat": "MAISON", "q": "Comment dire 'la maison où j'ai grandi' ?", "opts": ["la casa donde crecí", "la casa donde crezco", "la casa donde creceré", "la casa donde crecía"], "ans": 0},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "hay que limpiar la casa", "audioFr": "il faut nettoyer la maison", "words": ["hay", "que", "limpiar", "la", "casa", "comer"], "correct": ["hay", "que", "limpiar", "la", "casa"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "me gustaría comprar una casa", "audioFr": "j'aimerais acheter une maison", "words": ["me", "gustaría", "comprar", "una", "casa", "vender"], "correct": ["me", "gustaría", "comprar", "una", "casa"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "la casa donde crecí", "audioFr": "la maison où j'ai grandi", "words": ["la", "casa", "donde", "crecí", "vivo", "voy"], "correct": ["la", "casa", "donde", "crecí"]},
      {"type": "audio", "cat": "MAISON", "q": "Écoute et traduis la phrase", "audio": "es importante que esté limpia", "audioFr": "il est important qu'elle soit propre", "words": ["es", "importante", "que", "esté", "limpia", "está"], "correct": ["es", "importante", "que", "esté", "limpia"]},
    ],
  },

  verbes: {
    title: "Les verbes", icon: "📚",
    A0: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'manger' en espagnol ?", "opts": ["comer", "beber", "vivir", "ir"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'boire' ?", "opts": ["comer", "beber", "tener", "hacer"], "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'aller' ?", "opts": ["ir", "venir", "estar", "ser"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'avoir' ?", "opts": ["tener", "ser", "estar", "ir"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'être' (permanent) ?", "opts": ["ser", "estar", "tener", "ir"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'être' (temporaire) ?", "opts": ["ser", "estar", "ir", "tener"], "ans": 1},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "quiero comer", "audioFr": "je veux manger", "words": ["quiero", "comer", "beber", "ir", "tengo"], "correct": ["quiero", "comer"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "voy a beber", "audioFr": "je vais boire", "words": ["voy", "a", "beber", "comer", "tener"], "correct": ["voy", "a", "beber"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "tengo hambre", "audioFr": "j'ai faim", "words": ["tengo", "hambre", "sed", "soy", "voy"], "correct": ["tengo", "hambre"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "soy estudiante", "audioFr": "je suis étudiant", "words": ["soy", "estudiante", "estoy", "profesor", "voy"], "correct": ["soy", "estudiante"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je mange' ?", "opts": ["como", "comes", "come", "comemos"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'tu bois' ?", "opts": ["bebo", "bebes", "bebe", "bebemos"], "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'il va' ?", "opts": ["voy", "vas", "va", "vamos"], "ans": 2},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'nous avons' ?", "opts": ["tengo", "tienes", "tiene", "tenemos"], "ans": 3},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je suis' (temporaire) ?", "opts": ["soy", "estoy", "tengo", "voy"], "ans": 1},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'ils mangent' ?", "opts": ["como", "comes", "comen", "comemos"], "ans": 2},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "como en casa", "audioFr": "je mange à la maison", "words": ["como", "en", "casa", "voy", "tengo"], "correct": ["como", "en", "casa"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "bebes agua fría", "audioFr": "tu bois de l'eau froide", "words": ["bebes", "agua", "fría", "caliente", "comes"], "correct": ["bebes", "agua", "fría"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "vamos al cine", "audioFr": "nous allons au cinéma", "words": ["vamos", "al", "cine", "casa", "voy"], "correct": ["vamos", "al", "cine"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "tienen un coche", "audioFr": "ils ont une voiture", "words": ["tienen", "un", "coche", "casa", "soy"], "correct": ["tienen", "un", "coche"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'j'ai mangé' ?", "opts": ["he comido", "como", "comí", "comeré"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je mangeais' ?", "opts": ["comía", "como", "comí", "comeré"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'je vais manger' ?", "opts": ["voy a comer", "voy comer", "comer voy", "voy a comí"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Choisis la bonne phrase", "opts": ["quiero que vengas", "quiero que vienes", "quiero vienes", "quiero venir que"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'il faut que tu manges' ?", "opts": ["tienes que comer", "hay que comes", "es que comes", "tienes comer que"], "ans": 0},
      {"type": "mcq", "cat": "VERBES", "q": "Comment dire 'si j'avais le temps' ?", "opts": ["si tuviera tiempo", "si tengo tiempo", "si tenía tiempo", "si tuve tiempo"], "ans": 0},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "he terminado el trabajo", "audioFr": "j'ai terminé le travail", "words": ["he", "terminado", "el", "trabajo", "hoy", "voy"], "correct": ["he", "terminado", "el", "trabajo"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "voy a salir esta noche", "audioFr": "je vais sortir ce soir", "words": ["voy", "a", "salir", "esta", "noche", "ayer"], "correct": ["voy", "a", "salir", "esta", "noche"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "quiero que vengas conmigo", "audioFr": "je veux que tu viennes avec moi", "words": ["quiero", "que", "vengas", "conmigo", "vienes", "voy"], "correct": ["quiero", "que", "vengas", "conmigo"]},
      {"type": "audio", "cat": "VERBES", "q": "Écoute et traduis la phrase", "audio": "si tuviera tiempo viajaría", "audioFr": "si j'avais le temps je voyagerais", "words": ["si", "tuviera", "tiempo", "viajaría", "tengo", "voy"], "correct": ["si", "tuviera", "tiempo", "viajaría"]},
    ],
  },

  chiffres: {
    title: "Les chiffres", icon: "🔢",
    A0: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 1 en espagnol ?", "opts": ["uno", "dos", "tres", "cuatro"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 2 ?", "opts": ["uno", "dos", "tres", "cinco"], "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 3 ?", "opts": ["cuatro", "cinco", "tres", "dos"], "ans": 2},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 5 ?", "opts": ["cuatro", "cinco", "seis", "siete"], "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 10 ?", "opts": ["diez", "once", "doce", "trece"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 7 ?", "opts": ["seis", "siete", "ocho", "nueve"], "ans": 1},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "uno dos tres", "audioFr": "un deux trois", "words": ["uno", "dos", "tres", "cuatro", "cinco"], "correct": ["uno", "dos", "tres"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cinco seis", "audioFr": "cinq six", "words": ["cinco", "seis", "siete", "ocho", "nueve"], "correct": ["cinco", "seis"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "siete ocho", "audioFr": "sept huit", "words": ["siete", "ocho", "nueve", "diez", "uno"], "correct": ["siete", "ocho"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "nueve diez", "audioFr": "neuf dix", "words": ["nueve", "diez", "once", "doce", "tres"], "correct": ["nueve", "diez"]},
    ],
    A2: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 15 ?", "opts": ["quince", "catorce", "dieciséis", "trece"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 20 ?", "opts": ["veinte", "treinta", "cuarenta", "diez"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 30 ?", "opts": ["veinte", "treinta", "cuarenta", "cincuenta"], "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 50 ?", "opts": ["cuarenta", "cincuenta", "sesenta", "setenta"], "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 100 ?", "opts": ["cien", "mil", "diez", "ciento"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dit-on 200 ?", "opts": ["doscientos", "cien", "mil", "trescientos"], "ans": 0},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "tengo veinte años", "audioFr": "j'ai vingt ans", "words": ["tengo", "veinte", "años", "treinta", "soy"], "correct": ["tengo", "veinte", "años"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cuesta treinta euros", "audioFr": "ça coûte trente euros", "words": ["cuesta", "treinta", "euros", "veinte", "precio"], "correct": ["cuesta", "treinta", "euros"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "somos cinco personas", "audioFr": "nous sommes cinq personnes", "words": ["somos", "cinco", "personas", "dos", "gente"], "correct": ["somos", "cinco", "personas"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "hay cien casas", "audioFr": "il y a cent maisons", "words": ["hay", "cien", "casas", "mil", "dos"], "correct": ["hay", "cien", "casas"]},
    ],
    B1: [
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'mille' ?", "opts": ["mil", "millón", "cien", "ciento"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'un million' ?", "opts": ["mil", "millón", "cien", "millones"], "ans": 1},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'deux cents' ?", "opts": ["doscientos", "doscientas", "dos cien", "dos cientos"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Choisis la bonne phrase", "opts": ["hay más de cien personas", "hay más cien personas", "hay de más cien personas", "hay cien más personas"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'moins de vingt' ?", "opts": ["menos de veinte", "menos veinte", "veinte menos", "de menos veinte"], "ans": 0},
      {"type": "mcq", "cat": "CHIFFRES", "q": "Comment dire 'environ trente' ?", "opts": ["unos treinta", "treinta unos", "unos de treinta", "treinta de unos"], "ans": 0},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "hay más de cien personas", "audioFr": "il y a plus de cent personnes", "words": ["hay", "más", "de", "cien", "personas", "menos"], "correct": ["hay", "más", "de", "cien", "personas"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "cuesta unos treinta euros", "audioFr": "ça coûte environ trente euros", "words": ["cuesta", "unos", "treinta", "euros", "cien", "precio"], "correct": ["cuesta", "unos", "treinta", "euros"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "menos de veinte personas", "audioFr": "moins de vingt personnes", "words": ["menos", "de", "veinte", "personas", "más", "cien"], "correct": ["menos", "de", "veinte", "personas"]},
      {"type": "audio", "cat": "CHIFFRES", "q": "Écoute et traduis la phrase", "audio": "un millón de euros", "audioFr": "un million d'euros", "words": ["un", "millón", "de", "euros", "mil", "cien"], "correct": ["un", "millón", "de", "euros"]},
    ],
  },

  famille: {
    title: "La famille", icon: "👨‍👩‍👧",
    A0: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on père en espagnol ?", "opts": ["padre", "madre", "hermano", "abuelo"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on mère ?", "opts": ["padre", "madre", "hija", "tío"], "ans": 1},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on frère ?", "opts": ["hermano", "hermana", "padre", "hijo"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on sœur ?", "opts": ["hermano", "hermana", "madre", "tía"], "ans": 1},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on fils ?", "opts": ["hijo", "hija", "padre", "abuelo"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dit-on fille ?", "opts": ["hijo", "hija", "madre", "hermano"], "ans": 1},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi padre", "audioFr": "mon père", "words": ["mi", "padre", "madre", "tu", "hermano"], "correct": ["mi", "padre"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi madre", "audioFr": "ma mère", "words": ["mi", "madre", "padre", "hermana", "tu"], "correct": ["mi", "madre"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi hermano", "audioFr": "mon frère", "words": ["mi", "hermano", "hermana", "padre", "hijo"], "correct": ["mi", "hermano"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi hija", "audioFr": "ma fille", "words": ["mi", "hija", "hijo", "madre", "abuela"], "correct": ["mi", "hija"]},
    ],
    A2: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'ai un frère' ?", "opts": ["tengo un hermano", "soy un hermano", "estoy hermano", "voy hermano"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ma mère travaille' ?", "opts": ["mi madre trabaja", "mi madre trabajo", "mi madre trabajar", "trabaja madre"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'nous sommes une famille' ?", "opts": ["somos una familia", "soy una familia", "estamos familia", "tenemos familia"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'mon père est ici' ?", "opts": ["mi padre está aquí", "mi padre es aquí", "mi padre aquí es", "padre está aquí"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'aime ma famille' ?", "opts": ["me gusta mi familia", "me gusto mi familia", "me gustan familia", "gusta mi familia"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ils ont deux enfants' ?", "opts": ["tienen dos hijos", "tienen dos hijo", "tienen dos hijas", "tienen dos niño"], "ans": 0},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "tengo dos hermanos", "audioFr": "j'ai deux frères", "words": ["tengo", "dos", "hermanos", "hijas", "padre"], "correct": ["tengo", "dos", "hermanos"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi madre trabaja mucho", "audioFr": "ma mère travaille beaucoup", "words": ["mi", "madre", "trabaja", "mucho", "poco", "padre"], "correct": ["mi", "madre", "trabaja", "mucho"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "somos una familia grande", "audioFr": "nous sommes une grande famille", "words": ["somos", "una", "familia", "grande", "pequeña", "soy"], "correct": ["somos", "una", "familia", "grande"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "mi padre está en casa", "audioFr": "mon père est à la maison", "words": ["mi", "padre", "está", "en", "casa", "trabajo"], "correct": ["mi", "padre", "está", "en", "casa"]},
    ],
    B1: [
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'je m'entends bien avec ma famille' ?", "opts": ["me llevo bien con mi familia", "llevo bien mi familia", "me llevo con familia bien", "bien llevo familia"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'j'ai grandi avec mes grands-parents' ?", "opts": ["crecí con mis abuelos", "crezco con mis abuelos", "he crecido con mis abuelos", "crecía con mis abuelos"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Choisis la bonne phrase", "opts": ["es importante que la familia esté unida", "es importante que la familia está unida", "es importante la familia esté unida", "familia es importante unida"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'ma sœur vit à Madrid' ?", "opts": ["mi hermana vive en Madrid", "mi hermana vive a Madrid", "mi hermana está Madrid", "mi hermana vivir Madrid"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'je rendrai visite à mes parents' ?", "opts": ["visitaré a mis padres", "visito a mis padres", "voy visitar a mis padres", "visitaba a mis padres"], "ans": 0},
      {"type": "mcq", "cat": "FAMILLE", "q": "Comment dire 'nous nous voyons souvent' ?", "opts": ["nos vemos a menudo", "vemos a menudo", "nos vemos mucho a menudo", "vemos nos a menudo"], "ans": 0},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "me llevo bien con mi familia", "audioFr": "je m'entends bien avec ma famille", "words": ["me", "llevo", "bien", "con", "mi", "familia", "mal"], "correct": ["me", "llevo", "bien", "con", "mi", "familia"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "crecí con mis abuelos", "audioFr": "j'ai grandi avec mes grands-parents", "words": ["crecí", "con", "mis", "abuelos", "padres", "voy"], "correct": ["crecí", "con", "mis", "abuelos"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "visitaré a mis padres", "audioFr": "je rendrai visite à mes parents", "words": ["visitaré", "a", "mis", "padres", "visito", "ayer"], "correct": ["visitaré", "a", "mis", "padres"]},
      {"type": "audio", "cat": "FAMILLE", "q": "Écoute et traduis la phrase", "audio": "nos vemos a menudo", "audioFr": "nous nous voyons souvent", "words": ["nos", "vemos", "a", "menudo", "poco", "bien"], "correct": ["nos", "vemos", "a", "menudo"]},
    ],
  },

  voyage: {
    title: "Le voyage", icon: "✈️",
    A0: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on train en espagnol ?", "opts": ["tren", "avión", "coche", "barco"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on avion ?", "opts": ["barco", "tren", "avión", "taxi"], "ans": 2},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on hôtel ?", "opts": ["casa", "hotel", "calle", "ciudad"], "ans": 1},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on voiture ?", "opts": ["coche", "tren", "avión", "barco"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on billet ?", "opts": ["billete", "maleta", "viaje", "mapa"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dit-on valise ?", "opts": ["mapa", "maleta", "billete", "coche"], "ans": 1},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "tengo un billete", "audioFr": "j'ai un billet", "words": ["tengo", "un", "billete", "mapa", "viaje"], "correct": ["tengo", "un", "billete"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "el tren", "audioFr": "le train", "words": ["el", "tren", "avión", "coche", "barco"], "correct": ["el", "tren"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "la maleta", "audioFr": "la valise", "words": ["la", "maleta", "mapa", "casa", "hotel"], "correct": ["la", "maleta"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "el avión", "audioFr": "l'avion", "words": ["el", "avión", "tren", "coche", "taxi"], "correct": ["el", "avión"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je voyage en train' ?", "opts": ["viajo en tren", "voy en tren", "tengo tren", "viajo tren"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je prends l'avion' ?", "opts": ["tomo el avión", "como el avión", "voy avión", "tengo avión"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je vais à l'hôtel' ?", "opts": ["voy al hotel", "voy en hotel", "voy hotel", "estoy hotel"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je prépare ma valise' ?", "opts": ["preparo mi maleta", "preparo maleta", "tengo maleta", "voy maleta"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je pars demain' ?", "opts": ["salgo mañana", "voy mañana salir", "tengo salir mañana", "salir mañana voy"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je reste à l'hôtel' ?", "opts": ["me quedo en el hotel", "estoy en hotel", "voy en hotel", "tengo hotel"], "ans": 0},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "viajo en avión", "audioFr": "je voyage en avion", "words": ["viajo", "en", "avión", "tren", "coche"], "correct": ["viajo", "en", "avión"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "voy al hotel mañana", "audioFr": "je vais à l'hôtel demain", "words": ["voy", "al", "hotel", "mañana", "hoy", "casa"], "correct": ["voy", "al", "hotel", "mañana"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "preparo mi maleta", "audioFr": "je prépare ma valise", "words": ["preparo", "mi", "maleta", "mapa", "billete"], "correct": ["preparo", "mi", "maleta"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "me quedo en el hotel", "audioFr": "je reste à l'hôtel", "words": ["me", "quedo", "en", "el", "hotel", "voy"], "correct": ["me", "quedo", "en", "el", "hotel"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'j'aimerais réserver une chambre' ?", "opts": ["me gustaría reservar una habitación", "quiero reservar habitación", "voy reservar habitación", "tengo reservar habitación"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'j'ai perdu mon billet' ?", "opts": ["he perdido mi billete", "pierdo mi billete", "perdí mi billete", "perdía mi billete"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Choisis la phrase correcte", "opts": ["es mejor que reserves con antelación", "es mejor que reservas con antelación", "es mejor reservar que con antelación", "es mejor que reservar con antelación"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je vais voyager à l'étranger' ?", "opts": ["voy a viajar al extranjero", "voy viajar extranjero", "viajo extranjero", "viajaré extranjero voy"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'je suis déjà allé en Espagne' ?", "opts": ["ya he ido a España", "ya fui a España", "ya voy a España", "ya iba a España"], "ans": 0},
      {"type": "mcq", "cat": "VOYAGE", "q": "Comment dire 'nous avons réservé l'hôtel' ?", "opts": ["hemos reservado el hotel", "reservamos el hotel", "reservábamos el hotel", "reservaremos el hotel"], "ans": 0},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "me gustaría reservar una habitación", "audioFr": "j'aimerais réserver une chambre", "words": ["me", "gustaría", "reservar", "una", "habitación", "comprar"], "correct": ["me", "gustaría", "reservar", "una", "habitación"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "he perdido mi billete", "audioFr": "j'ai perdu mon billet", "words": ["he", "perdido", "mi", "billete", "maleta", "tengo"], "correct": ["he", "perdido", "mi", "billete"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "voy a viajar al extranjero", "audioFr": "je vais voyager à l'étranger", "words": ["voy", "a", "viajar", "al", "extranjero", "casa"], "correct": ["voy", "a", "viajar", "al", "extranjero"]},
      {"type": "audio", "cat": "VOYAGE", "q": "Écoute et traduis la phrase", "audio": "hemos reservado el hotel", "audioFr": "nous avons réservé l'hôtel", "words": ["hemos", "reservado", "el", "hotel", "mañana", "voy"], "correct": ["hemos", "reservado", "el", "hotel"]},
    ],
  },

  corps_sante: {
    title: "Corps et santé", icon: "🏥",
    A0: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on tête en espagnol ?", "opts": ["cabeza", "mano", "pie", "ojo"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on main ?", "opts": ["pie", "mano", "cabeza", "ojo"], "ans": 1},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on pied ?", "opts": ["mano", "cabeza", "pie", "ojo"], "ans": 2},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on oeil ?", "opts": ["nariz", "ojo", "boca", "mano"], "ans": 1},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on bouche ?", "opts": ["boca", "nariz", "ojo", "pie"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dit-on nez ?", "opts": ["nariz", "boca", "ojo", "mano"], "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "mi mano", "audioFr": "ma main", "words": ["mi", "mano", "pie", "cabeza", "ojo"], "correct": ["mi", "mano"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "la cabeza", "audioFr": "la tête", "words": ["la", "cabeza", "mano", "pie", "ojo"], "correct": ["la", "cabeza"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "el ojo", "audioFr": "l'oeil", "words": ["el", "ojo", "boca", "nariz", "mano"], "correct": ["el", "ojo"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "la boca", "audioFr": "la bouche", "words": ["la", "boca", "nariz", "ojo", "pie"], "correct": ["la", "boca"]},
    ],
    A2: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'ai mal à la tête' ?", "opts": ["tengo dolor de cabeza", "soy dolor de cabeza", "estoy dolor de cabeza", "voy dolor de cabeza"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'ai mal à la main' ?", "opts": ["tengo dolor de mano", "tengo mano dolor", "soy dolor mano", "estoy dolor de mano"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je suis malade' ?", "opts": ["estoy enfermo", "soy enfermo", "tengo enfermo", "voy enfermo"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je vais chez le médecin' ?", "opts": ["voy al médico", "voy médico", "soy médico", "tengo médico"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me sens bien' ?", "opts": ["me siento bien", "me siento bueno", "soy bien", "estoy bueno"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je suis fatigué' ?", "opts": ["estoy cansado", "soy cansado", "tengo cansado", "voy cansado"], "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tengo dolor de cabeza", "audioFr": "j'ai mal à la tête", "words": ["tengo", "dolor", "de", "cabeza", "mano", "pie"], "correct": ["tengo", "dolor", "de", "cabeza"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "estoy enfermo hoy", "audioFr": "je suis malade aujourd'hui", "words": ["estoy", "enfermo", "hoy", "mañana", "bien"], "correct": ["estoy", "enfermo", "hoy"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "voy al médico", "audioFr": "je vais chez le médecin", "words": ["voy", "al", "médico", "casa", "trabajo"], "correct": ["voy", "al", "médico"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "me siento cansado", "audioFr": "je me sens fatigué", "words": ["me", "siento", "cansado", "bien", "mal"], "correct": ["me", "siento", "cansado"]},
    ],
    B1: [
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je dois aller chez le médecin' ?", "opts": ["tengo que ir al médico", "voy ir al médico", "tengo ir médico", "debo voy médico"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me suis senti mieux' ?", "opts": ["me he sentido mejor", "me siento mejor", "me sentí mejor", "me sentía mejor"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Choisis la bonne phrase", "opts": ["es importante que descanses", "es importante que descansas", "es importante descansar que", "es importante descansas"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'j'avais mal hier' ?", "opts": ["tenía dolor ayer", "tengo dolor ayer", "tuve dolor ayer", "tenía dolor mañana"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'je me sens mieux aujourd'hui' ?", "opts": ["me siento mejor hoy", "soy mejor hoy", "estoy mejor hoy siento", "me mejor siento hoy"], "ans": 0},
      {"type": "mcq", "cat": "CORPS_SANTE", "q": "Comment dire 'il faut que tu te reposes' ?", "opts": ["tienes que descansar", "tienes descansar que", "descansar tienes que", "que tienes descansar"], "ans": 0},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tengo que ir al médico", "audioFr": "je dois aller chez le médecin", "words": ["tengo", "que", "ir", "al", "médico", "voy"], "correct": ["tengo", "que", "ir", "al", "médico"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "me he sentido mejor", "audioFr": "je me suis senti mieux", "words": ["me", "he", "sentido", "mejor", "peor", "soy"], "correct": ["me", "he", "sentido", "mejor"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "es importante que descanses", "audioFr": "il est important que tu te reposes", "words": ["es", "importante", "que", "descanses", "descansas", "bien"], "correct": ["es", "importante", "que", "descanses"]},
      {"type": "audio", "cat": "CORPS_SANTE", "q": "Écoute et traduis la phrase", "audio": "tenía dolor ayer", "audioFr": "j'avais mal hier", "words": ["tenía", "dolor", "ayer", "hoy", "tengo"], "correct": ["tenía", "dolor", "ayer"]},
    ],
  },

  metiers: {
    title: "Les métiers", icon: "💼",
    A0: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on médecin en espagnol ?", "opts": ["médico", "profesor", "ingeniero", "cocinero"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on professeur ?", "opts": ["médico", "profesor", "abogado", "policía"], "ans": 1},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on cuisinier ?", "opts": ["cocinero", "doctor", "maestro", "taxista"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on avocat ?", "opts": ["abogado", "ingeniero", "profesor", "policía"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on policier ?", "opts": ["policía", "bombero", "médico", "taxista"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dit-on chauffeur de taxi ?", "opts": ["taxista", "conductor", "piloto", "mecánico"], "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy médico", "audioFr": "je suis médecin", "words": ["soy", "médico", "profesor", "estoy", "trabajo"], "correct": ["soy", "médico"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy profesor", "audioFr": "je suis professeur", "words": ["soy", "profesor", "abogado", "médico", "trabajo"], "correct": ["soy", "profesor"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy cocinero", "audioFr": "je suis cuisinier", "words": ["soy", "cocinero", "taxista", "médico", "trabajo"], "correct": ["soy", "cocinero"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy policía", "audioFr": "je suis policier", "words": ["soy", "policía", "bombero", "taxista", "profesor"], "correct": ["soy", "policía"]},
    ],
    A2: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je suis ingénieur' ?", "opts": ["soy ingeniero", "estoy ingeniero", "tengo ingeniero", "voy ingeniero"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'elle est médecin' ?", "opts": ["es médica", "está médica", "soy médica", "tiene médica"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je travaille comme professeur' ?", "opts": ["trabajo como profesor", "soy trabajo profesor", "trabajo profesor como", "tengo profesor trabajo"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'il est policier' ?", "opts": ["es policía", "está policía", "soy policía", "tiene policía"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'nous sommes avocats' ?", "opts": ["somos abogados", "estamos abogados", "tenemos abogados", "vamos abogados"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je suis cuisinier' ?", "opts": ["soy cocinero", "estoy cocinero", "tengo cocinero", "voy cocinero"], "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "trabajo como ingeniero", "audioFr": "je travaille comme ingénieur", "words": ["trabajo", "como", "ingeniero", "médico", "soy"], "correct": ["trabajo", "como", "ingeniero"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "es médico en el hospital", "audioFr": "il est médecin à l'hôpital", "words": ["es", "médico", "en", "el", "hospital", "escuela"], "correct": ["es", "médico", "en", "el", "hospital"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "somos abogados", "audioFr": "nous sommes avocats", "words": ["somos", "abogados", "profesores", "médicos", "soy"], "correct": ["somos", "abogados"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "soy cocinero en un restaurante", "audioFr": "je suis cuisinier dans un restaurant", "words": ["soy", "cocinero", "en", "un", "restaurante", "casa"], "correct": ["soy", "cocinero", "en", "un", "restaurante"]},
    ],
    B1: [
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'j'aimerais devenir ingénieur' ?", "opts": ["me gustaría ser ingeniero", "quiero ser ingeniero", "voy ser ingeniero", "tengo ser ingeniero"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je travaille depuis deux ans' ?", "opts": ["trabajo desde hace dos años", "trabajo desde dos años", "trabajo hace dos años", "trabajo por dos años"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Choisis la bonne phrase", "opts": ["es importante que trabajes bien", "es importante que trabajas bien", "es importante trabajar que bien", "es importante trabajas bien"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'j'ai changé de travail' ?", "opts": ["he cambiado de trabajo", "cambio de trabajo", "cambié trabajo", "cambiaba de trabajo"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'je vais chercher un travail' ?", "opts": ["voy a buscar trabajo", "voy buscar trabajo", "busco voy trabajo", "voy trabajo buscar"], "ans": 0},
      {"type": "mcq", "cat": "METIERS", "q": "Comment dire 'il faut travailler dur' ?", "opts": ["hay que trabajar duro", "es trabajar duro", "tengo trabajar duro", "voy trabajar duro"], "ans": 0},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "me gustaría ser ingeniero", "audioFr": "j'aimerais devenir ingénieur", "words": ["me", "gustaría", "ser", "ingeniero", "trabajo", "soy"], "correct": ["me", "gustaría", "ser", "ingeniero"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "trabajo desde hace dos años", "audioFr": "je travaille depuis deux ans", "words": ["trabajo", "desde", "hace", "dos", "años", "meses"], "correct": ["trabajo", "desde", "hace", "dos", "años"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "he cambiado de trabajo", "audioFr": "j'ai changé de travail", "words": ["he", "cambiado", "de", "trabajo", "busco", "tengo"], "correct": ["he", "cambiado", "de", "trabajo"]},
      {"type": "audio", "cat": "METIERS", "q": "Écoute et traduis la phrase", "audio": "voy a buscar trabajo", "audioFr": "je vais chercher un travail", "words": ["voy", "a", "buscar", "trabajo", "encuentro", "tengo"], "correct": ["voy", "a", "buscar", "trabajo"]},
    ],
  },

  ville: {
    title: "La ville", icon: "🏙️",
    A0: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on ville en espagnol ?", "opts": ["ciudad", "calle", "plaza", "parque"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on rue ?", "opts": ["plaza", "calle", "ciudad", "parque"], "ans": 1},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on place ?", "opts": ["calle", "ciudad", "plaza", "parque"], "ans": 2},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on parc ?", "opts": ["parque", "calle", "plaza", "ciudad"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on magasin ?", "opts": ["tienda", "escuela", "hospital", "banco"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dit-on école ?", "opts": ["hospital", "escuela", "tienda", "banco"], "ans": 1},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la ciudad", "audioFr": "la ville", "words": ["la", "ciudad", "calle", "plaza", "parque"], "correct": ["la", "ciudad"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la calle", "audioFr": "la rue", "words": ["la", "calle", "plaza", "ciudad", "parque"], "correct": ["la", "calle"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "el parque", "audioFr": "le parc", "words": ["el", "parque", "calle", "plaza", "ciudad"], "correct": ["el", "parque"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la tienda", "audioFr": "le magasin", "words": ["la", "tienda", "escuela", "banco", "hospital"], "correct": ["la", "tienda"]},
    ],
    A2: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vais en ville' ?", "opts": ["voy a la ciudad", "voy ciudad", "voy en ciudad", "estoy ciudad"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'la rue est longue' ?", "opts": ["la calle es larga", "la calle está larga", "la calle larga es", "es calle larga"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je marche dans le parc' ?", "opts": ["camino en el parque", "voy parque", "camino parque", "estoy parque"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'le magasin est ouvert' ?", "opts": ["la tienda está abierta", "la tienda es abierta", "la tienda abierta es", "es tienda abierta"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vais à l'école' ?", "opts": ["voy a la escuela", "voy escuela", "voy en escuela", "estoy escuela"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'il y a un parc' ?", "opts": ["hay un parque", "es un parque", "tiene un parque", "está un parque"], "ans": 0},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "voy a la ciudad", "audioFr": "je vais en ville", "words": ["voy", "a", "la", "ciudad", "parque", "calle"], "correct": ["voy", "a", "la", "ciudad"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "camino en el parque", "audioFr": "je marche dans le parc", "words": ["camino", "en", "el", "parque", "calle", "voy"], "correct": ["camino", "en", "el", "parque"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la tienda está abierta", "audioFr": "le magasin est ouvert", "words": ["la", "tienda", "está", "abierta", "cerrada", "calle"], "correct": ["la", "tienda", "está", "abierta"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hay un parque", "audioFr": "il y a un parc", "words": ["hay", "un", "parque", "ciudad", "calle"], "correct": ["hay", "un", "parque"]},
    ],
    B1: [
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je vis dans une grande ville' ?", "opts": ["vivo en una gran ciudad", "vivo una ciudad grande", "soy en una ciudad grande", "estoy en gran ciudad"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'la ville où je suis né' ?", "opts": ["la ciudad donde nací", "la ciudad que nací", "la ciudad donde naceré", "la ciudad nací donde"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Choisis la bonne phrase", "opts": ["es mejor que vivas en el centro", "es mejor que vives en el centro", "es mejor vivir que en el centro", "es mejor que vivir en el centro"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'il y a beaucoup de monde en ville' ?", "opts": ["hay mucha gente en la ciudad", "hay mucho gente ciudad", "es mucha gente en ciudad", "tiene mucha gente ciudad"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'je me promène dans la rue' ?", "opts": ["paseo por la calle", "camino la calle", "voy por calle", "paseo calle"], "ans": 0},
      {"type": "mcq", "cat": "VILLE", "q": "Comment dire 'nous avons visité la ville' ?", "opts": ["hemos visitado la ciudad", "visitamos la ciudad", "visitábamos la ciudad", "visitaremos la ciudad"], "ans": 0},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "vivo en una gran ciudad", "audioFr": "je vis dans une grande ville", "words": ["vivo", "en", "una", "gran", "ciudad", "pueblo"], "correct": ["vivo", "en", "una", "gran", "ciudad"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "la ciudad donde nací", "audioFr": "la ville où je suis né", "words": ["la", "ciudad", "donde", "nací", "vivo", "voy"], "correct": ["la", "ciudad", "donde", "nací"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hay mucha gente en la ciudad", "audioFr": "il y a beaucoup de monde en ville", "words": ["hay", "mucha", "gente", "en", "la", "ciudad", "poco"], "correct": ["hay", "mucha", "gente", "en", "la", "ciudad"]},
      {"type": "audio", "cat": "VILLE", "q": "Écoute et traduis la phrase", "audio": "hemos visitado la ciudad", "audioFr": "nous avons visité la ville", "words": ["hemos", "visitado", "la", "ciudad", "mañana", "voy"], "correct": ["hemos", "visitado", "la", "ciudad"]},
    ],
  },

  adjectifs: {
    title: "Les adjectifs", icon: "🎨",
    A0: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on grand en espagnol ?", "opts": ["grande", "pequeño", "bonito", "rápido"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on petit ?", "opts": ["grande", "pequeño", "caro", "lento"], "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on beau ?", "opts": ["feo", "bonito", "caro", "lento"], "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on cher ?", "opts": ["barato", "caro", "bonito", "rápido"], "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on rapide ?", "opts": ["lento", "rápido", "grande", "caro"], "ans": 1},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dit-on lent ?", "opts": ["rápido", "lento", "bonito", "pequeño"], "ans": 1},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "coche grande", "audioFr": "voiture grande", "words": ["coche", "grande", "pequeño", "rápido", "caro"], "correct": ["coche", "grande"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "casa pequeña", "audioFr": "maison petite", "words": ["casa", "pequeña", "grande", "bonita", "cara"], "correct": ["casa", "pequeña"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "libro caro", "audioFr": "livre cher", "words": ["libro", "caro", "barato", "bonito", "rápido"], "correct": ["libro", "caro"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "coche rápido", "audioFr": "voiture rapide", "words": ["coche", "rápido", "lento", "grande", "caro"], "correct": ["coche", "rápido"]},
    ],
    A2: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'la maison est grande' ?", "opts": ["la casa es grande", "la casa está grande", "la casa grande es", "es casa grande"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le film est intéressant' ?", "opts": ["la película es interesante", "la película está interesante", "es película interesante", "película es interesante"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le prix est cher' ?", "opts": ["el precio es caro", "el precio está caro", "precio es caro", "es precio caro"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le service est rapide' ?", "opts": ["el servicio es rápido", "el servicio está rápido", "servicio es rápido", "es servicio rápido"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'la voiture est lente' ?", "opts": ["el coche es lento", "el coche está lento", "coche es lento", "es coche lento"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'le livre est bon' ?", "opts": ["el libro es bueno", "el libro está bueno", "libro es bueno", "es libro bueno"], "ans": 0},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "la casa es muy grande", "audioFr": "la maison est très grande", "words": ["la", "casa", "es", "muy", "grande", "pequeña"], "correct": ["la", "casa", "es", "muy", "grande"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el coche es muy rápido", "audioFr": "la voiture est très rapide", "words": ["el", "coche", "es", "muy", "rápido", "lento"], "correct": ["el", "coche", "es", "muy", "rápido"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el libro es interesante", "audioFr": "le livre est intéressant", "words": ["el", "libro", "es", "interesante", "aburrido", "caro"], "correct": ["el", "libro", "es", "interesante"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "el precio es caro", "audioFr": "le prix est cher", "words": ["el", "precio", "es", "caro", "barato", "grande"], "correct": ["el", "precio", "es", "caro"]},
    ],
    B1: [
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'il est important que ce soit rapide' ?", "opts": ["es importante que sea rápido", "es importante que es rápido", "es importante ser rápido", "es importante que está rápido"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'c'était très intéressant' ?", "opts": ["era muy interesante", "es muy interesante", "fue muy interesante", "será interesante"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Choisis la bonne phrase", "opts": ["es mejor que sea barato", "es mejor que es barato", "es mejor ser barato", "es mejor que está barato"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'il devient de plus en plus rapide' ?", "opts": ["se vuelve cada vez más rápido", "es cada vez rápido", "se vuelve más cada rápido", "es cada vez más rápido"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'je trouve ce film ennuyeux' ?", "opts": ["encuentro esta película aburrida", "encuentro película aburrido", "encuentro esta película aburrido", "película encuentro aburrida"], "ans": 0},
      {"type": "mcq", "cat": "ADJECTIFS", "q": "Comment dire 'c'est trop cher' ?", "opts": ["es demasiado caro", "es muy caro demasiado", "es caro muy", "es demasiado mucho caro"], "ans": 0},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "es importante que sea rápido", "audioFr": "il est important que ce soit rapide", "words": ["es", "importante", "que", "sea", "rápido", "está"], "correct": ["es", "importante", "que", "sea", "rápido"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "era muy interesante", "audioFr": "c'était très intéressant", "words": ["era", "muy", "interesante", "es", "fue"], "correct": ["era", "muy", "interesante"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "se vuelve cada vez más rápido", "audioFr": "il devient de plus en plus rapide", "words": ["se", "vuelve", "cada", "vez", "más", "rápido", "menos"], "correct": ["se", "vuelve", "cada", "vez", "más", "rápido"]},
      {"type": "audio", "cat": "ADJECTIFS", "q": "Écoute et traduis la phrase", "audio": "es demasiado caro", "audioFr": "c'est trop cher", "words": ["es", "demasiado", "caro", "muy", "barato"], "correct": ["es", "demasiado", "caro"]},
    ],
  },

  adverbes: {
    title: "Les adverbes", icon: "⚡",
    A0: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on très en espagnol ?", "opts": ["muy", "poco", "bien", "mal"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on bien ?", "opts": ["bien", "mal", "muy", "poco"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on mal ?", "opts": ["bien", "mal", "muy", "mucho"], "ans": 1},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on peu ?", "opts": ["mucho", "poco", "bien", "mal"], "ans": 1},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on beaucoup ?", "opts": ["mucho", "poco", "bien", "mal"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dit-on ici ?", "opts": ["aquí", "allí", "bien", "mal"], "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "muy bien", "audioFr": "très bien", "words": ["muy", "bien", "mal", "poco", "mucho"], "correct": ["muy", "bien"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "muy mal", "audioFr": "très mal", "words": ["muy", "mal", "bien", "poco", "mucho"], "correct": ["muy", "mal"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "mucho pan", "audioFr": "beaucoup de pain", "words": ["mucho", "pan", "poco", "bien", "mal"], "correct": ["mucho", "pan"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "aquí ahora", "audioFr": "ici maintenant", "words": ["aquí", "ahora", "allí", "mañana", "bien"], "correct": ["aquí", "ahora"]},
    ],
    A2: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je mange souvent' ?", "opts": ["como a menudo", "como siempre", "como mucho", "como poco"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille beaucoup' ?", "opts": ["trabajo mucho", "trabajo poco", "trabajo bien", "trabajo mal"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je parle bien' ?", "opts": ["hablo bien", "hablo mal", "hablo mucho", "hablo poco"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je dors mal' ?", "opts": ["duermo mal", "duermo bien", "duermo mucho", "duermo poco"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je viens ici' ?", "opts": ["vengo aquí", "vengo allí", "voy aquí", "voy allí"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je pars maintenant' ?", "opts": ["salgo ahora", "salgo mañana", "salgo ayer", "salgo siempre"], "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "como a menudo", "audioFr": "je mange souvent", "words": ["como", "a", "menudo", "siempre", "nunca"], "correct": ["como", "a", "menudo"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo mucho", "audioFr": "je travaille beaucoup", "words": ["trabajo", "mucho", "poco", "bien", "mal"], "correct": ["trabajo", "mucho"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "hablo bien español", "audioFr": "je parle bien espagnol", "words": ["hablo", "bien", "español", "mal", "poco"], "correct": ["hablo", "bien", "español"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "salgo ahora", "audioFr": "je pars maintenant", "words": ["salgo", "ahora", "mañana", "ayer", "siempre"], "correct": ["salgo", "ahora"]},
    ],
    B1: [
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille de plus en plus' ?", "opts": ["trabajo cada vez más", "trabajo más cada vez", "cada vez trabajo más", "trabajo vez más cada"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je ne viens jamais' ?", "opts": ["no vengo nunca", "no nunca vengo", "nunca no vengo", "vengo nunca no"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Choisis la bonne phrase", "opts": ["hablo bastante bien", "hablo bien bastante", "bastante hablo bien", "bien hablo bastante"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je comprends mieux maintenant' ?", "opts": ["entiendo mejor ahora", "entiendo ahora mejor", "mejor entiendo ahora", "entiendo ahora más mejor"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je travaille trop' ?", "opts": ["trabajo demasiado", "trabajo muy", "trabajo mucho demasiado", "trabajo demasiado mucho"], "ans": 0},
      {"type": "mcq", "cat": "ADVERBES", "q": "Comment dire 'je viens rarement' ?", "opts": ["vengo raramente", "raramente vengo", "vengo poco", "vengo siempre"], "ans": 0},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo cada vez más", "audioFr": "je travaille de plus en plus", "words": ["trabajo", "cada", "vez", "más", "menos", "poco"], "correct": ["trabajo", "cada", "vez", "más"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "no vengo nunca", "audioFr": "je ne viens jamais", "words": ["no", "vengo", "nunca", "siempre", "aquí"], "correct": ["no", "vengo", "nunca"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "entiendo mejor ahora", "audioFr": "je comprends mieux maintenant", "words": ["entiendo", "mejor", "ahora", "antes", "mal"], "correct": ["entiendo", "mejor", "ahora"]},
      {"type": "audio", "cat": "ADVERBES", "q": "Écoute et traduis la phrase", "audio": "trabajo demasiado", "audioFr": "je travaille trop", "words": ["trabajo", "demasiado", "mucho", "poco", "bien"], "correct": ["trabajo", "demasiado"]},
    ],
  },

  expressions: {
    title: "Expressions", icon: "💡",
    A0: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir faim' ?", "opts": ["tener hambre", "estar hambre", "ser hambre", "ir hambre"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir soif' ?", "opts": ["tener sed", "estar sed", "ser sed", "ir sed"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir chaud' ?", "opts": ["tener calor", "estar calor", "ser calor", "ir calor"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir froid' ?", "opts": ["tener frío", "estar frío", "ser frío", "ir frío"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir peur' ?", "opts": ["tener miedo", "estar miedo", "ser miedo", "ir miedo"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir raison' ?", "opts": ["tener razón", "estar razón", "ser razón", "ir razón"], "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo hambre", "audioFr": "j'ai faim", "words": ["tengo", "hambre", "sed", "frío", "calor"], "correct": ["tengo", "hambre"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo sed", "audioFr": "j'ai soif", "words": ["tengo", "sed", "hambre", "frío", "calor"], "correct": ["tengo", "sed"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo frío", "audioFr": "j'ai froid", "words": ["tengo", "frío", "calor", "hambre", "sed"], "correct": ["tengo", "frío"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "tengo calor", "audioFr": "j'ai chaud", "words": ["tengo", "calor", "frío", "hambre", "sed"], "correct": ["tengo", "calor"]},
    ],
    A2: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca m'est égal' ?", "opts": ["me da igual", "me es igual", "soy igual", "tengo igual"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'manquer' ?", "opts": ["echar de menos", "tener de menos", "ser de menos", "estar de menos"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'faire attention' ?", "opts": ["tener cuidado", "hacer cuidado", "ser cuidado", "estar cuidado"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'se dépêcher' ?", "opts": ["darse prisa", "hacer prisa", "tener prisa", "estar prisa"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'avoir besoin de' ?", "opts": ["tener que", "necesitar", "tener necesidad", "hacer falta"], "ans": 1},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'se rendre compte' ?", "opts": ["darse cuenta", "tener cuenta", "hacer cuenta", "estar cuenta"], "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "me da igual", "audioFr": "ca m'est égal", "words": ["me", "da", "igual", "bien", "mal"], "correct": ["me", "da", "igual"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "te echo de menos", "audioFr": "tu me manques", "words": ["te", "echo", "de", "menos", "más", "bien"], "correct": ["te", "echo", "de", "menos"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "ten cuidado", "audioFr": "fais attention", "words": ["ten", "cuidado", "prisa", "bien", "mal"], "correct": ["ten", "cuidado"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "date prisa", "audioFr": "dépêche-toi", "words": ["date", "prisa", "cuidado", "menos", "igual"], "correct": ["date", "prisa"]},
    ],
    B1: [
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca vaut la peine' ?", "opts": ["vale la pena", "vale pena", "es pena", "pena vale"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je m'en fiche' ?", "opts": ["me da igual", "me importa", "no me importa", "me gusta"], "ans": 2},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Choisis la bonne phrase", "opts": ["merece la pena intentarlo", "merece pena intentarlo", "pena merece intentarlo", "merece intentarlo pena"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je suis en train de le faire' ?", "opts": ["estoy haciéndolo", "soy haciendo", "estoy hacer", "hago lo"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'je n'en peux plus' ?", "opts": ["no puedo más", "no más puedo", "no puedo más de", "más no puedo"], "ans": 0},
      {"type": "mcq", "cat": "EXPRESSIONS", "q": "Comment dire 'ca dépend' ?", "opts": ["depende", "es depende", "tiene depende", "está depende"], "ans": 0},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "vale la pena", "audioFr": "ca vaut la peine", "words": ["vale", "la", "pena", "igual", "menos"], "correct": ["vale", "la", "pena"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "no puedo más", "audioFr": "je n'en peux plus", "words": ["no", "puedo", "más", "menos", "bien"], "correct": ["no", "puedo", "más"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "estoy haciéndolo", "audioFr": "je suis en train de le faire", "words": ["estoy", "haciéndolo", "hacer", "soy", "lo"], "correct": ["estoy", "haciéndolo"]},
      {"type": "audio", "cat": "EXPRESSIONS", "q": "Écoute et traduis la phrase", "audio": "depende de la situación", "audioFr": "ca dépend de la situation", "words": ["depende", "de", "la", "situación", "siempre", "nunca"], "correct": ["depende", "de", "la", "situación"]},
    ],
  },

};
